BARE2D: BARE2D::BARECEGUI Class Reference
BARE2D::BARECEGUI Class Reference
#include <BARECEGUI.hpp>
Public Member Functions
void init (std::string &resourceDirectory, unsigned int numContexts)
Initializes all of the necessary stuff to use CEGUI!
void draw ()
Draws the GUI to the screen over top of what's already there.
void update ()
Updates the amount of time passed in CEGUI.
void setActiveContext (unsigned int contextIndex)
Sets the active context.
void setMouseCursor (std::string imageFile)
Sets the image of the mouse cursor.
void setMouseCursorShown (bool shown)
Shows/hides the mouse cursor. Useful for cutscenes!
void handleSDLEvent (SDL_Event &evnt)
Handles and propagates input.
void loadScheme (std::string schemeFile)
Loads a scheme file from resourceDirectory/schemes.
void setFont (std::string fontFile)
Sets the current font to some font.
CEGUI::Window * createWidget (std::string type, glm::vec4 destRectPercent, glm::vec4 destRectPixels, CEGUI::Window *parent=nullptr, std::string name="")
Creates a widget of some type.
CEGUI::OpenGL3Renderer * getRenderer ()
CEGUI::GUIContext * getContext ()
Static Public Member Functions
static BARECEGUI * getInstance ()
static void release ()
Private Member Functions
BARECEGUI ()
~BARECEGUI ()
void destroy ()
Frees all necessary memory and unloads resources. Destroys root + children windows.
Private Attributes
std::vector< CEGUIContextWrapper * > m_contexts
unsigned int m_lastTime = 0
unsigned int m_activeContext = 0
Static Private Attributes
static BARECEGUI * m_instance = nullptr
static bool m_initialized = false
Detailed Description
Definition at line 17 of file BARECEGUI.hpp.
Constructor & Destructor Documentation
BARECEGUI()
BARE2D::BARECEGUI::BARECEGUI () private
Definition at line 26 of file BARECEGUI.cpp.
Referenced by getInstance().
~BARECEGUI()
BARE2D::BARECEGUI::~BARECEGUI () private
Definition at line 30 of file BARECEGUI.cpp.
Member Function Documentation
createWidget()
CEGUI::Window * BARE2D::BARECEGUI::createWidget (std::string type, glm::vec4 destRectPercent, glm::vec4 destRectPixels, CEGUI::Window * parent = nullptr, std::string name = "")
Creates a widget of some type.
Parameters
type The type of window - should generally be "[YourScheme]/[Label,Button,FrameWindow,etc.]". These strings are available in the scheme files.
destRectPercent The destination+rectangle of the widget, in terms of percentages of the screen.
destRectPixels The destination+rectangle of the widget, in terms of pixels.
parent The parent window - defaults to nullptr.
name The name of the window - defaults to a unique identifier. Only set this if a pointer of the window cannot be retained/propagated as a handle.
Returns
A pointer to the new CEGUI::Window - can be casted to some child type generally.
Definition at line 255 of file BARECEGUI.cpp.
destroy()
void BARE2D::BARECEGUI::destroy () private
Frees all necessary memory and unloads resources. Destroys root + children windows.
Definition at line 114 of file BARECEGUI.cpp.
draw()
void BARE2D::BARECEGUI::draw ()
Draws the GUI to the screen over top of what's already there.
Definition at line 125 of file BARECEGUI.cpp.
getContext()
CEGUI::GUIContext * BARE2D::BARECEGUI::getContext ()
Returns
The GUIContext that the context "owns"
Definition at line 277 of file BARECEGUI.cpp.
Referenced by BARE2D::App::pollSDLInput().
getInstance()
BARECEGUI * BARE2D::BARECEGUI::getInstance () static
Definition at line 14 of file BARECEGUI.cpp.
References BARECEGUI(), and m_instance.
Referenced by BARE2D::App::pollSDLInput().
getRenderer()
CEGUI::OpenGL3Renderer * BARE2D::BARECEGUI::getRenderer ()
Returns
The OpenGL3Renderer that the context "owns"
Definition at line 273 of file BARECEGUI.cpp.
handleSDLEvent()
void BARE2D::BARECEGUI::handleSDLEvent (SDL_Event & evnt)
Handles and propagates input.
Parameters
evnt The SDL_Event to add.
Definition at line 193 of file BARECEGUI.cpp.
Referenced by BARE2D::App::pollSDLInput().
init()
void BARE2D::BARECEGUI::init (std::string & resourceDirectory, unsigned int numContexts)
Initializes all of the necessary stuff to use CEGUI!
Parameters
resourceDirectory The directory that all of the resources lie in. Should follow CEGUI's specs.
numContexts The number of different contexts to create. Each context has the ability to handle input differently.
Definition at line 39 of file BARECEGUI.cpp.
References BARE2D::CEGUIContextWrapper::context, m_initialized, BARE2D::CEGUIContextWrapper::renderer, and BARE2D::CEGUIContextWrapper::rootWindow.
loadScheme()
void BARE2D::BARECEGUI::loadScheme (std::string schemeFile)
Loads a scheme file from resourceDirectory/schemes.
Parameters
schemeFile The file to load from
Definition at line 241 of file BARECEGUI.cpp.
release()
void BARE2D::BARECEGUI::release () static
Definition at line 21 of file BARECEGUI.cpp.
References m_instance.
setActiveContext()
void BARE2D::BARECEGUI::setActiveContext (unsigned int contextIndex)
Sets the active context.
Parameters
contextIndex The index of the context to activate. Must be less than numContexts from init().
Definition at line 173 of file BARECEGUI.cpp.
References m_activeContext.
setFont()
void BARE2D::BARECEGUI::setFont (std::string fontFile)
Sets the current font to some font.
Parameters
fontFile The file of the font to be loaded.
Definition at line 246 of file BARECEGUI.cpp.
setMouseCursor()
void BARE2D::BARECEGUI::setMouseCursor (std::string imageFile)
Sets the image of the mouse cursor.
Parameters
imageFile The file to set the mouse cursor's image from.
Definition at line 181 of file BARECEGUI.cpp.
setMouseCursorShown()
void BARE2D::BARECEGUI::setMouseCursorShown (bool shown)
Shows/hides the mouse cursor. Useful for cutscenes!
Parameters
shown True = shows the cursor, false = hides it.
Definition at line 185 of file BARECEGUI.cpp.
update()
void BARE2D::BARECEGUI::update ()
Updates the amount of time passed in CEGUI.
Definition at line 152 of file BARECEGUI.cpp.
References m_lastTime.
Member Data Documentation
m_activeContext
unsigned int BARE2D::BARECEGUI::m_activeContext = 0 private
Definition at line 111 of file BARECEGUI.hpp.
Referenced by setActiveContext().
m_contexts
std::vector<CEGUIContextWrapper*> BARE2D::BARECEGUI::m_contexts private
Definition at line 109 of file BARECEGUI.hpp.
m_initialized
bool BARE2D::BARECEGUI::m_initialized = false static private
Definition at line 102 of file BARECEGUI.hpp.
Referenced by init().
m_instance
BARECEGUI * BARE2D::BARECEGUI::m_instance = nullptr static private
Definition at line 100 of file BARECEGUI.hpp.
Referenced by getInstance(), and release().
m_lastTime
unsigned int BARE2D::BARECEGUI::m_lastTime = 0 private
Definition at line 110 of file BARECEGUI.hpp.
Referenced by update().
The documentation for this class was generated from the following files:
Source/BARECEGUI.hpp
Source/BARECEGUI.cpp