BARE2D: BARE2D::XMLData Class Reference
BARE2D::XMLData Class Reference
Holds all the very basic information for XML data. Designed to be a base class from which a user can derive custom data formats.
#include <XMLDataTypes.hpp>
Public Member Functions
XMLData ()
XMLData (std::string dataType, unsigned int ID)
XMLData (std::vector< AttributeBase * > attributes)
XMLData (std::unordered_map< std::string, AttributeBase * > attributes)
~XMLData ()
void read (rapidxml::xml_node<> *node)
Reads the entire piece of data from a given XML node.
void write (rapidxml::xml_document<> *doc)
Writes the entire piece of data to a new node in the XML document.
template<typename T >
T getAttributeByName (std::string name)
Finds an attribute by its name (eg. "name", "id")
std::unordered_map< std::string, AttributeBase * > getAttributes ()
Public Attributes
std::string name
unsigned int id
std::string nodeName
Protected Member Functions
template<typename T >
void addAttribute (std::string name, AttributeType type, T *data)
Constructs and adds an attribute to the data.
void addAttribute (AttributeBase *attr)
Adds an attribute to the data.
void addAttributes (std::vector< AttributeBase * > attrs)
Bulk adds attributes to the data.
Protected Attributes
std::unordered_map< std::string, AttributeBase * > m_attributes
Detailed Description
Holds all the very basic information for XML data. Designed to be a base class from which a user can derive custom data formats.
Definition at line 102 of file XMLDataTypes.hpp.
Constructor & Destructor Documentation
XMLData() [1/4]
BARE2D::XMLData::XMLData ()
Definition at line 159 of file XMLDataTypes.cpp.
References addAttribute(), id, name, BARE2D::STRING, and BARE2D::UNSIGNED_INT.
Referenced by XMLData().
XMLData() [2/4]
BARE2D::XMLData::XMLData (std::string dataType, unsigned int ID)
Definition at line 165 of file XMLDataTypes.cpp.
References BARE2D::XMLDataManager::getData(), id, m_attributes, name, and BARE2D::AttributeBase::swapDataPointer().
XMLData() [3/4]
BARE2D::XMLData::XMLData (std::vector< AttributeBase * > attributes)
Definition at line 173 of file XMLDataTypes.cpp.
References addAttribute(), addAttributes(), id, name, BARE2D::STRING, BARE2D::UNSIGNED_INT, and XMLData().
XMLData() [4/4]
BARE2D::XMLData::XMLData (std::unordered_map< std::string, AttributeBase * > attributes)
Definition at line 182 of file XMLDataTypes.cpp.
References m_attributes, and XMLData().
~XMLData()
BARE2D::XMLData::~XMLData () inline
Definition at line 108 of file XMLDataTypes.hpp.
Member Function Documentation
addAttribute() [1/2]
void BARE2D::XMLData::addAttribute (AttributeBase * attr) protected
Adds an attribute to the data.
Parameters
attr A pointer to the attribute to be added.
Definition at line 357 of file XMLDataTypes.cpp.
References m_attributes, and BARE2D::AttributeBase::name.
Referenced by addAttributes().
addAttribute() [2/2]
template<typename T > void BARE2D::XMLData::addAttribute (std::string name, AttributeType type, T * data) protected
Constructs and adds an attribute to the data.
Parameters
name The name of the attribute. "name" and "id" are already in use, please don't break things like that.
type The type of data. Eg. AttributeType::FLOAT is a float, AttributeType::VECTOR_FLOAT is a vector of floats, etc.
data A pointer to the data that the attribute is linked to.
Definition at line 110 of file XMLDataTypes.tcc.
References m_attributes.
Referenced by XMLData().
addAttributes()
void BARE2D::XMLData::addAttributes (std::vector< AttributeBase * > attrs) protected
Bulk adds attributes to the data.
Parameters
attrs A vector of pointers to attributes to add.
Definition at line 361 of file XMLDataTypes.cpp.
References addAttribute().
Referenced by XMLData().
getAttributeByName()
template<typename T > T BARE2D::XMLData::getAttributeByName (std::string name)
Finds an attribute by its name (eg. "name", "id")
Parameters
name The name of the attribute
Returns
A copy of the data held by the attribute.
Definition at line 96 of file XMLDataTypes.tcc.
References m_attributes, BARE2D::throwError(), and BARE2D::XML_FAILURE.
getAttributes()
std::unordered_map< std::string, AttributeBase * > BARE2D::XMLData::getAttributes ()
Returns
Returns a copy of the entire attributes map. Useful for pseudo-copy operations.
Definition at line 353 of file XMLDataTypes.cpp.
References m_attributes.
read()
void BARE2D::XMLData::read (rapidxml::xml_node<> * node)
Reads the entire piece of data from a given XML node.
Parameters
node The node to interpret and read from
Definition at line 187 of file XMLDataTypes.cpp.
References BARE2D::BOOL, BARE2D::FLOAT, id, BARE2D::INT, m_attributes, name, BARE2D::XMLDataManager::readValue(), BARE2D::AttributeBase::setData(), BARE2D::STRING, BARE2D::throwError(), BARE2D::AttributeBase::type, BARE2D::UNSIGNED_INT, BARE2D::VEC2, BARE2D::VECTOR_BOOL, BARE2D::VECTOR_FLOAT, BARE2D::VECTOR_UNSIGNED_INT, BARE2D::VECTOR_VEC2, and BARE2D::XML_FAILURE.
Referenced by BARE2D::XMLDataManager::readXMLData().
write()
void BARE2D::XMLData::write (rapidxml::xml_document<> * doc)
Writes the entire piece of data to a new node in the XML document.
Parameters
doc The document to write to.
Definition at line 300 of file XMLDataTypes.cpp.
References BARE2D::AttributeBase::getDataString(), id, m_attributes, name, and nodeName.
Referenced by BARE2D::XMLDataManager::writeXMLData().
Member Data Documentation
id
unsigned int BARE2D::XMLData::id
Definition at line 135 of file XMLDataTypes.hpp.
Referenced by BARE2D::XMLDataManager::addData(), read(), BARE2D::XMLDataManager::readXMLData(), write(), BARE2D::XMLDataManager::writeXMLData(), and XMLData().
m_attributes
std::unordered_map<std::string, AttributeBase*> BARE2D::XMLData::m_attributes protected
Definition at line 159 of file XMLDataTypes.hpp.
Referenced by addAttribute(), getAttributeByName(), getAttributes(), read(), write(), and XMLData().
name
std::string BARE2D::XMLData::name
Definition at line 134 of file XMLDataTypes.hpp.
Referenced by read(), BARE2D::XMLDataManager::readXMLData(), write(), BARE2D::XMLDataManager::writeXMLData(), and XMLData().
nodeName
std::string BARE2D::XMLData::nodeName
Definition at line 136 of file XMLDataTypes.hpp.
Referenced by BARE2D::XMLDataManager::addData(), BARE2D::XMLDataManager::readXMLData(), write(), and BARE2D::XMLDataManager::writeXMLData().
The documentation for this class was generated from the following files:
Source/XMLDataTypes.hpp
Source/XMLDataTypes.tcc
Source/XMLDataTypes.cpp