BARE2D: BARE2D::InputManager Class Reference
BARE2D::InputManager Class Reference
This is the input manager. It does what you expect! Nearly completely copied from GLEngine, the ol' gal.
#include <InputManager.hpp>
Public Member Functions
InputManager ()
~InputManager ()
void update ()
Updates the inputmanager. Should be called every frame.
void pressKey (unsigned int keyID)
Sets a key as 'pressed'.
void releaseKey (unsigned int keyID)
Sets a key as 'released'.
void setMousePosition (float x, float y)
Sets the mouse position to (x,y)
void setMousePosition (glm::vec2 position)
Sets the mouse position to 'position'.
void setMouseScrollwheelPosition (int position)
Sets the "position" of the scrollwheel - essentially, how much it has moved since the last frame.
bool isKeyDown (unsigned int keyID) const
Checks if the key is down at all.
bool isKeyPressed (unsigned int keyID) const
Checks if the key has just been pressed.
glm::vec2 getMousePosition () const
Gets the position of the mouse in the window.
int getMouseScrollwheelPosition () const
Gets the position of the mousewheel.
Private Member Functions
bool wasKeyDown (unsigned int keyID) const
Checks if the key was down last frame.
Private Attributes
std::unordered_map< unsigned int, bool > m_keyMap
std::unordered_map< unsigned int, bool > m_previousKeyMap
glm::vec2 m_mousePosition
int m_mouseScrollwheelPosition = 0
Detailed Description
This is the input manager. It does what you expect! Nearly completely copied from GLEngine, the ol' gal.
Definition at line 12 of file InputManager.hpp.
Constructor & Destructor Documentation
InputManager()
BARE2D::InputManager::InputManager ()
Definition at line 5 of file InputManager.cpp.
Referenced by BARE2D::App::init().
~InputManager()
BARE2D::InputManager::~InputManager ()
Definition at line 10 of file InputManager.cpp.
Member Function Documentation
getMousePosition()
glm::vec2 BARE2D::InputManager::getMousePosition () const
Gets the position of the mouse in the window.
Returns
The position of the mouse in a glm::vec2
Definition at line 75 of file InputManager.cpp.
References m_mousePosition.
getMouseScrollwheelPosition()
int BARE2D::InputManager::getMouseScrollwheelPosition () const
Gets the position of the mousewheel.
Returns
How much the mousewheel has moved since last update.
Definition at line 80 of file InputManager.cpp.
References m_mouseScrollwheelPosition.
isKeyDown()
bool BARE2D::InputManager::isKeyDown (unsigned int keyID) const
Checks if the key is down at all.
Parameters
keyID The SDL-given ID to check against
Returns
true if the key is down
Definition at line 54 of file InputManager.cpp.
References m_keyMap.
Referenced by isKeyPressed().
isKeyPressed()
bool BARE2D::InputManager::isKeyPressed (unsigned int keyID) const
Checks if the key has just been pressed.
Parameters
keyID The SDL-given ID to check against
Returns
true if the key wasn't down last frame and is this frame. false otherwise
Definition at line 69 of file InputManager.cpp.
References isKeyDown(), and wasKeyDown().
pressKey()
void BARE2D::InputManager::pressKey (unsigned int keyID)
Sets a key as 'pressed'.
Parameters
keyID The id given for a key by SDL
Definition at line 26 of file InputManager.cpp.
References m_keyMap.
Referenced by BARE2D::App::pollSDLInput().
releaseKey()
void BARE2D::InputManager::releaseKey (unsigned int keyID)
Sets a key as 'released'.
Parameters
keyID The id given for a key by SDL
Definition at line 32 of file InputManager.cpp.
References m_keyMap.
Referenced by BARE2D::App::pollSDLInput().
setMousePosition() [1/2]
void BARE2D::InputManager::setMousePosition (float x, float y)
Sets the mouse position to (x,y)
Parameters
x A float to represent x position
y A float to represent y position
Definition at line 38 of file InputManager.cpp.
References m_mousePosition.
Referenced by BARE2D::App::pollSDLInput().
setMousePosition() [2/2]
void BARE2D::InputManager::setMousePosition (glm::vec2 position)
Sets the mouse position to 'position'.
Parameters
position The position to set it to.
Definition at line 44 of file InputManager.cpp.
References m_mousePosition.
setMouseScrollwheelPosition()
void BARE2D::InputManager::setMouseScrollwheelPosition (int position)
Sets the "position" of the scrollwheel - essentially, how much it has moved since the last frame.
Parameters
position The distance it has moved since last update.
Definition at line 49 of file InputManager.cpp.
References m_mouseScrollwheelPosition.
Referenced by BARE2D::App::pollSDLInput().
update()
void BARE2D::InputManager::update ()
Updates the inputmanager. Should be called every frame.
Definition at line 15 of file InputManager.cpp.
References m_keyMap, m_mouseScrollwheelPosition, and m_previousKeyMap.
Referenced by BARE2D::App::updateInput().
wasKeyDown()
bool BARE2D::InputManager::wasKeyDown (unsigned int keyID) const private
Checks if the key was down last frame.
Parameters
keyID The SDL-given ID to check against
Returns
true if the key was down last frame, false otherwise.
Definition at line 85 of file InputManager.cpp.
References m_previousKeyMap.
Referenced by isKeyPressed().
Member Data Documentation
m_keyMap
std::unordered_map<unsigned int, bool> BARE2D::InputManager::m_keyMap private
Definition at line 88 of file InputManager.hpp.
Referenced by isKeyDown(), pressKey(), releaseKey(), and update().
m_mousePosition
glm::vec2 BARE2D::InputManager::m_mousePosition private
Definition at line 90 of file InputManager.hpp.
Referenced by getMousePosition(), and setMousePosition().
m_mouseScrollwheelPosition
int BARE2D::InputManager::m_mouseScrollwheelPosition = 0 private
Definition at line 91 of file InputManager.hpp.
Referenced by getMouseScrollwheelPosition(), setMouseScrollwheelPosition(), and update().
m_previousKeyMap
std::unordered_map<unsigned int, bool> BARE2D::InputManager::m_previousKeyMap private
Definition at line 89 of file InputManager.hpp.
Referenced by update(), and wasKeyDown().
The documentation for this class was generated from the following files:
Source/InputManager.hpp
Source/InputManager.cpp