BARE2D: BARE2D::AttributeBase Class Reference
BARE2D::AttributeBase Class Reference abstract
The AttributeBase class only exists for some templating acrobatics reasons (as an abstract base class for Attribute)
#include <XMLDataTypes.hpp>
Public Member Functions
template<typename T >
void setData (T data)
template<typename T >
T getData ()
template<typename T >
T * getDataPointer ()
template<typename T >
void swapDataPointer (T *newPtr)
virtual ~AttributeBase ()
virtual std::string getDataString ()=0
Public Attributes
std::string name
AttributeType type
Protected Member Functions
virtual void setDefaultData ()=0
Detailed Description
The AttributeBase class only exists for some templating acrobatics reasons (as an abstract base class for Attribute)
Definition at line 27 of file XMLDataTypes.hpp.
Constructor & Destructor Documentation
~AttributeBase()
virtual BARE2D::AttributeBase::~AttributeBase () inline virtual
Definition at line 41 of file XMLDataTypes.hpp.
Member Function Documentation
getData()
template<typename T > T BARE2D::AttributeBase::getData
Definition at line 15 of file XMLDataTypes.cpp.
getDataPointer()
template<typename T > T * BARE2D::AttributeBase::getDataPointer
Definition at line 26 of file XMLDataTypes.cpp.
getDataString()
virtual std::string BARE2D::AttributeBase::getDataString () pure virtual
Implemented in BARE2D::Attribute< T >, BARE2D::Attribute< T >, BARE2D::Attribute< T >, BARE2D::Attribute< T >, BARE2D::Attribute< T >, BARE2D::Attribute< T >, BARE2D::Attribute< T >, BARE2D::Attribute< T >, BARE2D::Attribute< T >, BARE2D::Attribute< T >, BARE2D::Attribute< T >, BARE2D::Attribute< T >, BARE2D::Attribute< T >, BARE2D::Attribute< T >, BARE2D::Attribute< T >, BARE2D::Attribute< T >, BARE2D::Attribute< T >, BARE2D::Attribute< T >, BARE2D::Attribute< T >, BARE2D::Attribute< T >, BARE2D::Attribute< T >, BARE2D::Attribute< T >, BARE2D::Attribute< T >, BARE2D::Attribute< T >, and BARE2D::Attribute< T >.
Referenced by BARE2D::XMLData::write().
setData()
template<typename T > void BARE2D::AttributeBase::setData (T data)
Definition at line 9 of file XMLDataTypes.cpp.
Referenced by BARE2D::XMLData::read().
setDefaultData()
virtual void BARE2D::AttributeBase::setDefaultData () protected pure virtual
Implemented in BARE2D::Attribute< T >, BARE2D::Attribute< T >, BARE2D::Attribute< T >, BARE2D::Attribute< T >, BARE2D::Attribute< T >, BARE2D::Attribute< T >, BARE2D::Attribute< T >, BARE2D::Attribute< T >, BARE2D::Attribute< T >, BARE2D::Attribute< T >, BARE2D::Attribute< T >, BARE2D::Attribute< T >, BARE2D::Attribute< T >, BARE2D::Attribute< T >, BARE2D::Attribute< T >, BARE2D::Attribute< T >, BARE2D::Attribute< T >, BARE2D::Attribute< T >, BARE2D::Attribute< T >, BARE2D::Attribute< T >, BARE2D::Attribute< T >, BARE2D::Attribute< T >, BARE2D::Attribute< T >, BARE2D::Attribute< T >, and BARE2D::Attribute< T >.
swapDataPointer()
template<typename T > void BARE2D::AttributeBase::swapDataPointer (T * newPtr)
Definition at line 21 of file XMLDataTypes.cpp.
Referenced by BARE2D::XMLData::XMLData().
Member Data Documentation
name
std::string BARE2D::AttributeBase::name
Definition at line 43 of file XMLDataTypes.hpp.
Referenced by BARE2D::XMLData::addAttribute(), and BARE2D::Attribute< T >::Attribute().
type
AttributeType BARE2D::AttributeBase::type
Definition at line 44 of file XMLDataTypes.hpp.
Referenced by BARE2D::Attribute< T >::Attribute(), and BARE2D::XMLData::read().
The documentation for this class was generated from the following files:
Source/XMLDataTypes.hpp
Source/XMLDataTypes.cpp