BARE2D: BARE2D::DebugRenderer Class Reference
BARE2D::DebugRenderer Class Reference
#include <DebugRenderer.hpp>
Public Member Functions
DebugRenderer ()
virtual ~DebugRenderer ()
virtual void init () override
Initializes with very rudimentary shaders (hardcoded), adds vertex attributes.
virtual void begin () override
Clears the necessary vectors, etc. to prepare for draw() calls, etc.
virtual void render () override
Actually renders the contents to the screen!
virtual void drawLine (glm::vec2 point0, glm::vec2 point1, float thickness, Colour colour)
Draws a line.
virtual void drawCircle (glm::vec2 centre, float lineThickness, float radius, Colour fillColour=Colour(255, 255, 255, 255))
Draws a circle.
virtual void drawRectangle (glm::vec4 destRect, float lineThickness, Colour fillColour=Colour(255, 255, 255, 255))
Draws a rectangle.
Public Member Functions inherited from BARE2D::Renderer
Renderer ()
virtual ~Renderer ()
virtual void end ()
Creates the renderbatches, does necessary stuff before render() call.
virtual void initUniforms ()
Initializes all uniforms, such as colour attachments, depth attachments, etc.
virtual void destroy ()
Frees all necessary memory.
ShaderProgram * getShader ()
Protected Member Functions
virtual void createRenderBatches () override
Constructs all of the render batches from data given by, say, draw() calls.
Protected Member Functions inherited from BARE2D::Renderer
virtual void preRender ()
Does stuff inside of the render function, within the shader's use.
virtual void link (std::initializer_list< std::string > attributes)
Protected Attributes
std::vector< Line > m_lines
std::vector< Circle > m_circles
std::vector< Rectangle > m_rectangles
Protected Attributes inherited from BARE2D::Renderer
ShaderProgram m_shader
VAO m_vertexArrayObject
std::vector< RenderBatch > m_batches
Detailed Description
Author
Davis-Dev
Date
10/08/23
Definition at line 42 of file DebugRenderer.hpp.
Constructor & Destructor Documentation
DebugRenderer()
BARE2D::DebugRenderer::DebugRenderer ()
Definition at line 68 of file DebugRenderer.cpp.
~DebugRenderer()
BARE2D::DebugRenderer::~DebugRenderer () virtual
Definition at line 71 of file DebugRenderer.cpp.
Member Function Documentation
begin()
void BARE2D::DebugRenderer::begin () override virtual
Clears the necessary vectors, etc. to prepare for draw() calls, etc.
Reimplemented from BARE2D::Renderer.
Definition at line 90 of file DebugRenderer.cpp.
References BARE2D::Renderer::begin(), m_circles, m_lines, and m_rectangles.
createRenderBatches()
void BARE2D::DebugRenderer::createRenderBatches () override protected virtual
Constructs all of the render batches from data given by, say, draw() calls.
Implements BARE2D::Renderer.
Definition at line 113 of file DebugRenderer.cpp.
References BARE2D::VAO::bindVBO(), BARE2D::Line::colour, BARE2D::Vertex::colour, BARE2D::Circle::lines, BARE2D::Rectangle::lines, m_circles, m_lines, m_rectangles, BARE2D::Renderer::m_vertexArrayObject, BARE2D::Circle::origin, BARE2D::Line::point0, BARE2D::Line::point1, and BARE2D::Vertex::setPosition().
drawCircle()
void BARE2D::DebugRenderer::drawCircle (glm::vec2 centre, float lineThickness, float radius, Colour fillColour = Colour(255, 255, 255, 255)) virtual
Draws a circle.
Parameters
centre The centre point of the circle
lineThickness The thickness of the lines creating the circle
radius The radius of the circle
lineColour The colour of the lines
fillColour The fill of the circle
Definition at line 103 of file DebugRenderer.cpp.
References BARE2D::Circle::construct(), and m_circles.
drawLine()
void BARE2D::DebugRenderer::drawLine (glm::vec2 point0, glm::vec2 point1, float thickness, Colour colour) virtual
Draws a line.
Parameters
point0 The origin
point1 Where the line goes to
thickness The thickness of the line
colour The colour of the line
Definition at line 98 of file DebugRenderer.cpp.
References BARE2D::Line::construct(), and m_lines.
drawRectangle()
void BARE2D::DebugRenderer::drawRectangle (glm::vec4 destRect, float lineThickness, Colour fillColour = Colour(255, 255, 255, 255)) virtual
Draws a rectangle.
Parameters
destRect The destination rectangle of the rectangle (position, then size)
lineColour The colour of the lines that make up the rectangle
fillColour The colour of the fill.
Definition at line 108 of file DebugRenderer.cpp.
References BARE2D::Rectangle::construct(), and m_rectangles.
init()
void BARE2D::DebugRenderer::init () override virtual
Initializes with very rudimentary shaders (hardcoded), adds vertex attributes.
Reimplemented from BARE2D::Renderer.
Definition at line 74 of file DebugRenderer.cpp.
References BARE2D::VAO::addVertexAttribute(), BARE2D::Vertex::colour, BARE2D::ShaderProgram::compileShadersFromSource(), fragShaderSource, BARE2D::Renderer::init(), BARE2D::Renderer::link(), BARE2D::Renderer::m_shader, BARE2D::Renderer::m_vertexArrayObject, BARE2D::Vertex::position, and vertShaderSource.
render()
void BARE2D::DebugRenderer::render () override virtual
Actually renders the contents to the screen!
Reimplemented from BARE2D::Renderer.
Definition at line 196 of file DebugRenderer.cpp.
References BARE2D::VAO::bind(), BARE2D::GLContextManager::getContext(), m_circles, m_lines, m_rectangles, BARE2D::Renderer::m_shader, BARE2D::Renderer::m_vertexArrayObject, BARE2D::GLContext::setActiveTexture(), BARE2D::Line::thickness, BARE2D::VAO::unbind(), BARE2D::ShaderProgram::unuse(), and BARE2D::ShaderProgram::use().
Field Documentation
m_circles
std::vector<Circle> BARE2D::DebugRenderer::m_circles protected
Definition at line 87 of file DebugRenderer.hpp.
Referenced by begin(), createRenderBatches(), drawCircle(), and render().
m_lines
std::vector<Line> BARE2D::DebugRenderer::m_lines protected
Definition at line 86 of file DebugRenderer.hpp.
Referenced by begin(), createRenderBatches(), drawLine(), and render().
m_rectangles
std::vector<Rectangle> BARE2D::DebugRenderer::m_rectangles protected
Definition at line 88 of file DebugRenderer.hpp.
Referenced by begin(), createRenderBatches(), drawRectangle(), and render().
The documentation for this class was generated from the following files:
Source/DebugRenderer.hpp
Source/DebugRenderer.cpp