BARE2D: BARE2D::XMLDataManager Class Reference
BARE2D::XMLDataManager Class Reference
A singleton class that statically manages all XML data, including read and write operations.
#include <XMLDataManager.hpp>
Public Member Functions
template<>
bool readValue (rapidxml::xml_node<> *parent, std::string valueName, std::string &variable)
template<>
bool readValue (rapidxml::xml_node<> *parent, std::string valueName, unsigned int &variable)
template<>
bool readValue (rapidxml::xml_node<> *parent, std::string valueName, std::vector< unsigned int > &variable)
template<>
bool readValue (rapidxml::xml_node<> *parent, std::string valueName, int &variable)
template<>
bool readValue (rapidxml::xml_node<> *parent, std::string valueName, float &variable)
template<>
bool readValue (rapidxml::xml_node<> *parent, std::string valueName, std::vector< float > &variable)
template<>
bool readValue (rapidxml::xml_node<> *parent, std::string valueName, bool &variable)
template<>
bool readValue (rapidxml::xml_node<> *parent, std::string valueName, std::vector< bool > &variable)
template<>
bool readValue (rapidxml::xml_node<> *parent, std::string valueName, glm::vec2 &variable)
template<>
bool readValue (rapidxml::xml_node<> *parent, std::string valueName, std::vector< glm::vec2 > &variable)
Static Public Member Functions
static void loadXML (std::string filepath)
Loads all of the files from the filepath that end in .xml to the caches. Does not clear caches.
static void saveXML (std::string filepath)
Writes all of the currently cached data to the data's respective files in a folder at filepath. Does not clear caches.
template<typename T >
static void addDataType ()
Adds a type of data that can be read. Make sure that the custom data type's nodeName is set.
static void addData (XMLData *data)
Adds a piece of data to the cache, in the appropriate sub-cache.
template<typename T >
static T getData (std::string dataType, unsigned int key)
Finds some data in the subcache.
static unsigned int getDataCount (std::string dataType)
static void clearCache ()
Clears the various caches and subcaches that the class uses. Useful for refreshes.
static XMLData getDataType (std::string dataType)
Provides a copy of some data type added by the addDataType function.
Static Private Member Functions
static void writeXMLData (std::ofstream &file, Cache< unsigned int, XMLData > *data)
Writes a single subcache of data to a single file.
static void readXMLData (std::ifstream &file, std::string dataType)
Reads a single subcache from a single file.
template<typename T >
static bool readValue (rapidxml::xml_node<> *parent, std::string valueName, T &variable)
Reads a value from a node. Templated for almost any primitive.
static Cache< unsigned int, XMLData > * getDataCache (std::string dataType)
Returns a cache for a certain type of data.
Static Private Attributes
static Cache< std::string, Cache< unsigned int, XMLData > > m_storedData
static Cache< std::string, XMLData > m_dataTypes
Friends
class XMLData
Detailed Description
A singleton class that statically manages all XML data, including read and write operations.
Definition at line 15 of file XMLDataManager.hpp.
Member Function Documentation
addData()
void BARE2D::XMLDataManager::addData (XMLData * data) static
Adds a piece of data to the cache, in the appropriate sub-cache.
Parameters
data A pointer to the data to be added. data->nodeName must be set for appropriate sub-caching.
Definition at line 133 of file XMLDataManager.cpp.
References BARE2D::Cache< S, T >::createItem(), BARE2D::Cache< S, T >::findItem(), getDataCache(), BARE2D::XMLData::id, and BARE2D::XMLData::nodeName.
Referenced by readXMLData().
addDataType()
template<typename T > void BARE2D::XMLDataManager::addDataType static
Adds a type of data that can be read. Make sure that the custom data type's nodeName is set.
Definition at line 33 of file XMLDataManager.tcc.
References BARE2D::Cache< S, T >::createItem(), and m_dataTypes.
clearCache()
void BARE2D::XMLDataManager::clearCache () static
Clears the various caches and subcaches that the class uses. Useful for refreshes.
Definition at line 432 of file XMLDataManager.cpp.
References BARE2D::Cache< S, T >::clear(), m_dataTypes, and m_storedData.
getData()
template<typename T > T BARE2D::XMLDataManager::getData (std::string dataType, unsigned int key) static
Finds some data in the subcache.
Parameters
dataType The string type of the data to get.
key The ID of the data.
Returns
A copy of the data, as nobody should be modifying the cached data.
Definition at line 6 of file XMLDataManager.tcc.
References BARE2D::Cache< S, T >::findItem(), and getDataCache().
Referenced by BARE2D::XMLData::XMLData().
getDataCache()
Cache< unsigned int, XMLData > * BARE2D::XMLDataManager::getDataCache (std::string dataType) static private
Returns a cache for a certain type of data.
Parameters
dataType The string type of the data
Returns
A pointer to the subcache.
Definition at line 422 of file XMLDataManager.cpp.
References BARE2D::Cache< S, T >::createItem(), BARE2D::Logger::getInstance(), BARE2D::Logger::log(), m_storedData, and BARE2D::Cache< S, T >::operator[]().
Referenced by addData(), getData(), and getDataCount().
getDataCount()
unsigned int BARE2D::XMLDataManager::getDataCount (std::string dataType) static
Parameters
dataType The string type of the data to get info on.
Returns
The number of elements of the type of data.
Definition at line 129 of file XMLDataManager.cpp.
References BARE2D::Cache< S, T >::getCount(), and getDataCache().
getDataType()
XMLData BARE2D::XMLDataManager::getDataType (std::string dataType) static
Provides a copy of some data type added by the addDataType function.
Parameters
dataType The string identifier for the type of data. In other words, nodeName
Returns
A copy of some type of data, complete with nodeName and attributes set.
Definition at line 145 of file XMLDataManager.cpp.
References BARE2D::Cache< S, T >::findItem(), and m_dataTypes.
loadXML()
void BARE2D::XMLDataManager::loadXML (std::string filepath) static
Loads all of the files from the filepath that end in .xml to the caches. Does not clear caches.
Parameters
filepath The path of the folder of files to load, or the path of an actual singular file to load.
Definition at line 17 of file XMLDataManager.cpp.
References BARE2D::Filesystem::getFilesIn(), BARE2D::Logger::getInstance(), BARE2D::Logger::log(), readXMLData(), BARE2D::throwFatalError(), and BARE2D::XML_FAILURE.
readValue() [1/11]
template<> bool BARE2D::XMLDataManager::readValue (rapidxml::xml_node<> * parent, std::string valueName, bool & variable)
Definition at line 300 of file XMLDataManager.cpp.
References BARE2D::throwError(), and BARE2D::XML_FAILURE.
readValue() [2/11]
template<> bool BARE2D::XMLDataManager::readValue (rapidxml::xml_node<> * parent, std::string valueName, float & variable)
Definition at line 243 of file XMLDataManager.cpp.
References BARE2D::throwError(), and BARE2D::XML_FAILURE.
readValue() [3/11]
template<> bool BARE2D::XMLDataManager::readValue (rapidxml::xml_node<> * parent, std::string valueName, glm::vec2 & variable)
Definition at line 357 of file XMLDataManager.cpp.
References BARE2D::throwError(), and BARE2D::XML_FAILURE.
readValue() [4/11]
template<> bool BARE2D::XMLDataManager::readValue (rapidxml::xml_node<> * parent, std::string valueName, int & variable)
Definition at line 225 of file XMLDataManager.cpp.
References BARE2D::throwError(), and BARE2D::XML_FAILURE.
readValue() [5/11]
template<> bool BARE2D::XMLDataManager::readValue (rapidxml::xml_node<> * parent, std::string valueName, std::string & variable)
Definition at line 150 of file XMLDataManager.cpp.
References BARE2D::throwError(), and BARE2D::XML_FAILURE.
readValue() [6/11]
template<> bool BARE2D::XMLDataManager::readValue (rapidxml::xml_node<> * parent, std::string valueName, std::vector< bool > & variable)
Definition at line 318 of file XMLDataManager.cpp.
References BARE2D::throwError(), and BARE2D::XML_FAILURE.
readValue() [7/11]
template<> bool BARE2D::XMLDataManager::readValue (rapidxml::xml_node<> * parent, std::string valueName, std::vector< float > & variable)
Definition at line 261 of file XMLDataManager.cpp.
References BARE2D::throwError(), and BARE2D::XML_FAILURE.
readValue() [8/11]
template<> bool BARE2D::XMLDataManager::readValue (rapidxml::xml_node<> * parent, std::string valueName, std::vector< glm::vec2 > & variable)
Definition at line 382 of file XMLDataManager.cpp.
References BARE2D::throwError(), and BARE2D::XML_FAILURE.
readValue() [9/11]
template<> bool BARE2D::XMLDataManager::readValue (rapidxml::xml_node<> * parent, std::string valueName, std::vector< unsigned int > & variable)
Definition at line 186 of file XMLDataManager.cpp.
References BARE2D::throwError(), and BARE2D::XML_FAILURE.
readValue() [10/11]
template<typename T > static bool BARE2D::XMLDataManager::readValue (rapidxml::xml_node<> * parent, std::string valueName, T & variable) static private
Reads a value from a node. Templated for almost any primitive.
Parameters
parent A pointer to the node of the parent data.
valueName The "nodeName" of the value to be read.
variable The return variable.
Returns
True on success, false on failure.
Referenced by BARE2D::XMLData::read().
readValue() [11/11]
template<> bool BARE2D::XMLDataManager::readValue (rapidxml::xml_node<> * parent, std::string valueName, unsigned int & variable)
Definition at line 168 of file XMLDataManager.cpp.
References BARE2D::throwError(), and BARE2D::XML_FAILURE.
readXMLData()
void BARE2D::XMLDataManager::readXMLData (std::ifstream & file, std::string dataType) static private
Reads a single subcache from a single file.
Parameters
file The file to read from.
dataType The nodeName of the data to read. This will be the key for the cache.
Definition at line 50 of file XMLDataManager.cpp.
References addData(), BARE2D::Cache< S, T >::findItem(), BARE2D::Logger::getInstance(), BARE2D::XMLData::id, BARE2D::Logger::log(), m_dataTypes, BARE2D::XMLData::name, BARE2D::XMLData::nodeName, and BARE2D::XMLData::read().
Referenced by loadXML().
saveXML()
void BARE2D::XMLDataManager::saveXML (std::string filepath) static
Writes all of the currently cached data to the data's respective files in a folder at filepath. Does not clear caches.
Parameters
filepath The path of the folder of files to save.
Definition at line 85 of file XMLDataManager.cpp.
References BARE2D::Logger::getInstance(), BARE2D::Logger::log(), m_storedData, BARE2D::throwFatalError(), writeXMLData(), and BARE2D::XML_FAILURE.
writeXMLData()
void BARE2D::XMLDataManager::writeXMLData (std::ofstream & file, Cache< unsigned int, XMLData > * data) static private
Writes a single subcache of data to a single file.
Parameters
file The file to write the data to
data A pointer to the subcache to write
Definition at line 109 of file XMLDataManager.cpp.
References BARE2D::Logger::getInstance(), BARE2D::XMLData::id, BARE2D::Logger::log(), BARE2D::XMLData::name, BARE2D::XMLData::nodeName, and BARE2D::XMLData::write().
Referenced by saveXML().
Friends And Related Function Documentation
XMLData
friend class XMLData friend
Definition at line 17 of file XMLDataManager.hpp.
Member Data Documentation
m_dataTypes
Cache< std::string, XMLData > BARE2D::XMLDataManager::m_dataTypes static private
Definition at line 103 of file XMLDataManager.hpp.
Referenced by addDataType(), clearCache(), getDataType(), and readXMLData().
m_storedData
Cache< std::string, Cache< unsigned int, XMLData > > BARE2D::XMLDataManager::m_storedData static private
Definition at line 102 of file XMLDataManager.hpp.
Referenced by clearCache(), getDataCache(), and saveXML().
The documentation for this class was generated from the following files:
Source/XMLDataManager.hpp
Source/XMLDataManager.cpp
Source/XMLDataManager.tcc