BARE2D: BARE2D::Glyph Class Reference
BARE2D::Glyph Class Reference
The glyph represents a renderbatch's primitive data, which is created from each draw call in the basic renderer.
#include <Vertex.hpp>
Public Member Functions
Glyph (glm::vec4 &destRect, glm::vec4 &uvRect, GLuint &Texture, float &Depth, Colour &colour)
Glyph (glm::vec4 &destRect, glm::vec4 &uvRect, GLuint &Texture, float &Depth, Colour &colour, float &angle)
Glyph (glm::vec4 &destRect, glm::vec4 &uvRect, GLuint &Texture, float &Depth, Colour &colour, float &angle, glm::vec2 &COR)
Public Attributes
GLuint texture
float depth
Vertex topLeft
Vertex bottomLeft
Vertex topRight
Vertex bottomRight
Protected Member Functions
glm::vec2 rotatePoint (const glm::vec2 &pos, float &angle)
Detailed Description
The glyph represents a renderbatch's primitive data, which is created from each draw call in the basic renderer.
Definition at line 87 of file Vertex.hpp.
Constructor & Destructor Documentation
Glyph() [1/3]
BARE2D::Glyph::Glyph (glm::vec4 & destRect, glm::vec4 & uvRect, GLuint & Texture, float & Depth, Colour & colour)
Definition at line 4 of file Vertex.cpp.
References bottomLeft, bottomRight, BARE2D::Vertex::colour, depth, BARE2D::Vertex::setPosition(), BARE2D::Vertex::setUV(), texture, topLeft, and topRight.
Referenced by BARE2D::FBORenderer::createRenderBatches().
Glyph() [2/3]
BARE2D::Glyph::Glyph (glm::vec4 & destRect, glm::vec4 & uvRect, GLuint & Texture, float & Depth, Colour & colour, float & angle)
Definition at line 22 of file Vertex.cpp.
References bottomLeft, bottomRight, BARE2D::Vertex::colour, depth, rotatePoint(), BARE2D::Vertex::setPosition(), BARE2D::Vertex::setUV(), texture, topLeft, and topRight.
Glyph() [3/3]
BARE2D::Glyph::Glyph (glm::vec4 & destRect, glm::vec4 & uvRect, GLuint & Texture, float & Depth, Colour & colour, float & angle, glm::vec2 & COR)
Definition at line 54 of file Vertex.cpp.
References bottomLeft, bottomRight, BARE2D::Vertex::colour, depth, rotatePoint(), BARE2D::Vertex::setPosition(), BARE2D::Vertex::setUV(), texture, topLeft, and topRight.
Referenced by BARE2D::BumpyGlyph::BumpyGlyph(), and BARE2D::BasicRenderer::draw().
Member Function Documentation
rotatePoint()
glm::vec2 BARE2D::Glyph::rotatePoint (const glm::vec2 & pos, float & angle) protected
Definition at line 87 of file Vertex.cpp.
Referenced by Glyph().
Member Data Documentation
bottomLeft
Vertex BARE2D::Glyph::bottomLeft
Definition at line 100 of file Vertex.hpp.
Referenced by BARE2D::BasicRenderer::createRenderBatches(), BARE2D::BumpyRenderer::createRenderBatches(), BARE2D::FBORenderer::createRenderBatches(), and Glyph().
bottomRight
Vertex BARE2D::Glyph::bottomRight
Definition at line 100 of file Vertex.hpp.
Referenced by BARE2D::BasicRenderer::createRenderBatches(), BARE2D::BumpyRenderer::createRenderBatches(), BARE2D::FBORenderer::createRenderBatches(), and Glyph().
depth
float BARE2D::Glyph::depth
Definition at line 97 of file Vertex.hpp.
Referenced by Glyph().
texture
GLuint BARE2D::Glyph::texture
Definition at line 94 of file Vertex.hpp.
Referenced by BARE2D::BasicRenderer::createRenderBatches(), BARE2D::BumpyRenderer::createRenderBatches(), BARE2D::FBORenderer::createRenderBatches(), and Glyph().
topLeft
Vertex BARE2D::Glyph::topLeft
Definition at line 100 of file Vertex.hpp.
Referenced by BARE2D::BasicRenderer::createRenderBatches(), BARE2D::BumpyRenderer::createRenderBatches(), BARE2D::FBORenderer::createRenderBatches(), and Glyph().
topRight
Vertex BARE2D::Glyph::topRight
Definition at line 100 of file Vertex.hpp.
Referenced by BARE2D::BasicRenderer::createRenderBatches(), BARE2D::BumpyRenderer::createRenderBatches(), BARE2D::FBORenderer::createRenderBatches(), and Glyph().
The documentation for this class was generated from the following files:
Source/Vertex.hpp
Source/Vertex.cpp