BARE2D: BARE2D::GLContextManager Class Reference
BARE2D::GLContextManager Class Reference
#include <GLContextManager.hpp>
Static Public Member Functions
static GLContext * getContext ()
Static Private Attributes
static GLContext * m_context = nullptr
Detailed Description
Definition at line 42 of file GLContextManager.hpp.
Member Function Documentation
getContext()
GLContext * BARE2D::GLContextManager::getContext () static
Definition at line 44 of file GLContextManager.cpp.
References m_context.
Referenced by BARE2D::FBORenderer::bind(), BARE2D::ResourceManager::createMutableTexture(), BARE2D::FBORenderer::createTextures(), BARE2D::TexturelessRenderer::init(), BARE2D::Font::init(), BARE2D::ResourceManager::loadTexture(), BARE2D::FBORenderer::preRender(), BARE2D::BumpyRenderer::render(), BARE2D::FBORenderer::render(), BARE2D::Renderer::render(), BARE2D::DebugRenderer::render(), BARE2D::MutableTexture::setData(), and BARE2D::FBORenderer::unbind().
Field Documentation
m_context
GLContext * BARE2D::GLContextManager::m_context = nullptr static private
Definition at line 48 of file GLContextManager.hpp.
Referenced by getContext().
The documentation for this class was generated from the following files:
GLContextManager.hpp
GLContextManager.cpp