BARE2D: BARE2D::App Class Reference
BARE2D::App Class Reference
#include <App.hpp>
Public Member Functions
App ()
~App ()
void run ()
Runs the program! Starts the update-draw loop.
ScreenList * getScreenList ()
Returns the screen list, where the program can add more screens, set entry points, etc.
Window * getWindow ()
InputManager * getInputManager ()
Private Member Functions
void init ()
Initializes the applet and engine. Creates a window, held within this App. Only for internal use.
void update (double dt)
Updates input, output, etc. Only for internal use.
void draw ()
Draws the current screen, based on that screen's drawing protocol.
void updateInput ()
Updates any input, and throws it down the pipeline!
void pollSDLInput ()
Polls inputs from SDL and updates the inputmanager as appropriate.
void exitApp ()
Calls the screen's exit function, and then cleans this class up for destruction.
Private Attributes
bool m_isGameRunning = false
bool m_isInited = false
std::unique_ptr< ScreenList > m_screenList
InputManager * m_inputManager = nullptr
Timer * m_timer = nullptr
Window * m_window = nullptr
Detailed Description
Definition at line 19 of file App.hpp.
Constructor & Destructor Documentation
App()
BARE2D::App::App ()
Definition at line 13 of file App.cpp.
References init().
~App()
BARE2D::App::~App ()
Definition at line 18 of file App.cpp.
References exitApp(), m_isGameRunning, and m_window.
Member Function Documentation
draw()
void BARE2D::App::draw () private
Draws the current screen, based on that screen's drawing protocol.
Definition at line 127 of file App.cpp.
References BARE2D::Screen::draw(), BARE2D::ScreenList::getCurrentScreen(), BARE2D::Window::getHeight(), BARE2D::Screen::getState(), BARE2D::Window::getWidth(), m_screenList, m_window, and BARE2D::RUNNING.
Referenced by run().
exitApp()
void BARE2D::App::exitApp () private
Calls the screen's exit function, and then cleans this class up for destruction.
Definition at line 172 of file App.cpp.
References m_isGameRunning.
Referenced by pollSDLInput(), update(), and ~App().
getInputManager()
InputManager * BARE2D::App::getInputManager ()
Returns
The input manager pointer.
Definition at line 71 of file App.cpp.
References m_inputManager.
getScreenList()
ScreenList * BARE2D::App::getScreenList ()
Returns the screen list, where the program can add more screens, set entry points, etc.
Definition at line 62 of file App.cpp.
References m_screenList.
getWindow()
Window * BARE2D::App::getWindow ()
Returns
Returns a pointer to the window, so that the client can change its size, title, etc.
Definition at line 67 of file App.cpp.
References m_window.
init()
void BARE2D::App::init () private
Initializes the applet and engine. Creates a window, held within this App. Only for internal use.
Definition at line 76 of file App.cpp.
References BARE2D::Window::create(), BARE2D::DOUBLE_INIT, BARE2D::init(), BARE2D::InputManager::InputManager(), m_inputManager, m_isInited, m_timer, m_window, BARE2D::Timer::setDeltaTimeLimit(), BARE2D::throwFatalError(), BARE2D::Timer::Timer(), and BARE2D::Window::Window().
Referenced by App(), and run().
pollSDLInput()
void BARE2D::App::pollSDLInput () private
Polls inputs from SDL and updates the inputmanager as appropriate.
Definition at line 143 of file App.cpp.
References exitApp(), m_inputManager, BARE2D::InputManager::pressKey(), BARE2D::InputManager::releaseKey(), BARE2D::InputManager::setMousePosition(), and BARE2D::InputManager::setMouseScrollwheelPosition().
Referenced by updateInput().
run()
void BARE2D::App::run ()
Runs the program! Starts the update-draw loop.
Definition at line 26 of file App.cpp.
References draw(), BARE2D::Timer::endTimer(), BARE2D::ScreenList::getCurrentScreen(), BARE2D::Timer::getDeltaTime(), init(), BARE2D::Timer::integrateFrame(), m_isGameRunning, m_isInited, m_screenList, m_timer, m_window, BARE2D::Screen::onEntry(), BARE2D::Screen::onExit(), BARE2D::Timer::startTimer(), BARE2D::Window::swapBuffer(), and update().
update()
void BARE2D::App::update (double dt) private
Updates input, output, etc. Only for internal use.
Definition at line 105 of file App.cpp.
References BARE2D::CHANGE_NEXT, BARE2D::CHANGE_PREV, BARE2D::EXIT_APPLICATION, exitApp(), BARE2D::ScreenList::getCurrentScreen(), BARE2D::Screen::getState(), m_screenList, BARE2D::ScreenList::moveToNextScreen(), BARE2D::ScreenList::moveToPreviousScreen(), BARE2D::RUNNING, BARE2D::Screen::update(), and updateInput().
Referenced by run().
updateInput()
void BARE2D::App::updateInput () private
Updates any input, and throws it down the pipeline!
Definition at line 136 of file App.cpp.
References m_inputManager, pollSDLInput(), and BARE2D::InputManager::update().
Referenced by update().
Member Data Documentation
m_inputManager
InputManager* BARE2D::App::m_inputManager = nullptr private
Definition at line 51 of file App.hpp.
Referenced by getInputManager(), init(), pollSDLInput(), and updateInput().
m_isGameRunning
bool BARE2D::App::m_isGameRunning = false private
Definition at line 46 of file App.hpp.
Referenced by exitApp(), run(), and ~App().
m_isInited
bool BARE2D::App::m_isInited = false private
Definition at line 47 of file App.hpp.
Referenced by init(), and run().
m_screenList
std::unique_ptr<ScreenList> BARE2D::App::m_screenList private
Definition at line 49 of file App.hpp.
Referenced by draw(), getScreenList(), run(), and update().
m_timer
Timer* BARE2D::App::m_timer = nullptr private
Definition at line 53 of file App.hpp.
Referenced by init(), and run().
m_window
Window* BARE2D::App::m_window = nullptr private
Definition at line 55 of file App.hpp.
Referenced by draw(), getWindow(), init(), run(), and ~App().
The documentation for this class was generated from the following files:
Source/App.hpp
Source/App.cpp