BARE2D: BARE2D::FontRenderer Class Reference
BARE2D::FontRenderer Class Reference
The FontRenderer... renders fonts. It is just a very basic extension of the BasicRenderer, so it works the same.
#include <FontRenderer.hpp>
Public Member Functions
FontRenderer (std::string &fragShader, std::string &vertShader, unsigned int perspectiveWidth=2, unsigned int perspectiveHeight=2)
~FontRenderer ()
virtual void draw (Font &font, glm::vec2 scaling, glm::vec4 destRect, const char *text, float depth, Colour tint, Justification just=Justification::LEFT, glm::vec4 uvRect=glm::vec4(0.0f, 0.0f, 1.0f, 1.0f))
Public Member Functions inherited from BARE2D::BasicRenderer
BasicRenderer (std::string &fragShader, std::string &vertShader, unsigned int perspectiveWidth=2, unsigned int perspectiveHeight=2)
virtual ~BasicRenderer ()
virtual void init () override
Initializes all necessary bits of the renderer.
virtual void preRender () override
Does stuff inside of the render function, within the shader's use.
virtual void setCamera (std::shared_ptr< Camera2D > camera)
Sets the camera to a given pointer. This means that the renderer takes ownership.
std::shared_ptr< Camera2D > getCamera ()
virtual void draw (glm::vec4 destRect, glm::vec4 uvRect, GLuint texture, float depth, Colour colour=Colour(255, 255, 255, 255), float angle=0.0f, glm::vec2 COR=glm::vec2(0.5f))
Public Member Functions inherited from BARE2D::Renderer
Renderer ()
virtual ~Renderer ()
virtual void begin ()
Clears the necessary vectors, etc. to prepare for draw() calls, etc.
virtual void end ()
Creates the renderbatches, does necessary stuff before render() call.
virtual void init ()
Initializes all necessary bits of the renderer.
virtual void initUniforms ()
Initializes all uniforms, such as colour attachments, depth attachments, etc.
virtual void destroy ()
Frees all necessary memory.
virtual void render ()
Actually renders the contents to the screen!
ShaderProgram * getShader ()
Additional Inherited Members
Protected Member Functions inherited from BARE2D::BasicRenderer
virtual void createRenderBatches () override
Constructs all of the render batches from data given by, say, draw() calls.
Protected Member Functions inherited from BARE2D::Renderer
virtual void preRender ()
Does stuff inside of the render function, within the shader's use.
virtual void link (std::initializer_list< std::string > attributes)
virtual void createRenderBatches ()=0
Constructs all of the render batches from data given by, say, draw() calls.
Protected Attributes inherited from BARE2D::BasicRenderer
std::string m_fragShader
std::string m_vertShader
std::vector< Glyph * > m_glyphs
std::shared_ptr< Camera2D > m_camera
Protected Attributes inherited from BARE2D::Renderer
ShaderProgram m_shader
VAO m_vertexArrayObject
std::vector< RenderBatch > m_batches
Detailed Description
The FontRenderer... renders fonts. It is just a very basic extension of the BasicRenderer, so it works the same.
Definition at line 22 of file FontRenderer.hpp.
Constructor & Destructor Documentation
FontRenderer()
BARE2D::FontRenderer::FontRenderer (std::string & fragShader, std::string & vertShader, unsigned int perspectiveWidth = 2, unsigned int perspectiveHeight = 2)
Definition at line 5 of file FontRenderer.cpp.
~FontRenderer()
BARE2D::FontRenderer::~FontRenderer ()
Definition at line 12 of file FontRenderer.cpp.
Member Function Documentation
draw()
void BARE2D::FontRenderer::draw (Font & font, glm::vec2 scaling, glm::vec4 destRect, const char * text, float depth, Colour tint, Justification just = Justification::LEFT, glm::vec4 uvRect = glm::vec4(0.0f, 0.0f, 1.0f, 1.0f)) virtual
Parameters
just = Justification::LEFT
uvRect = glm::vec4(0.0f, 0.0f, 1.0f, 1.0f)
Definition at line 15 of file FontRenderer.cpp.
References BARE2D::BasicRenderer::draw(), FIRST_PRINTABLE_CHAR, BARE2D::Font::getCharacters(), BARE2D::Font::getGlyph(), BARE2D::Font::getHeight(), BARE2D::Font::getTextureID(), BARE2D::Font::measure(), BARE2D::MIDDLE, BARE2D::RIGHT, BARE2D::CharacterGlyph::size, and BARE2D::CharacterGlyph::uvRect.
The documentation for this class was generated from the following files:
Source/FontRenderer.hpp
Source/FontRenderer.cpp