BARE2D: BARE2D::LuaScriptQueue Class Reference
BARE2D::LuaScriptQueue Class Reference
#include <LuaScriptQueue.hpp>
Public Member Functions
unsigned int addLuaScript (LuaScript &script)
Adds a script to the queue to be run.
unsigned int addLuaScript (std::string script)
Adds a script to the queue to be run by its source code.
std::map< unsigned int, LuaScript * > & getQueue ()
Returns the queue of scripts to activate.
void clearQueue ()
Clears the stored script queue - for regular use by tbe Script Engine. Deallocates memory that was in use in the m_scripts map.
Static Public Member Functions
static LuaScriptQueue * getInstance ()
Returns a pointer to the singleton object - creates the object if one doesn't already exist.
static void destroyInstance ()
Destroys the singleton.
Private Member Functions
LuaScriptQueue ()
~LuaScriptQueue ()
Private Attributes
std::map< unsigned int, LuaScript * > m_scripts
unsigned int m_lastUUID = -1
Static Private Attributes
static LuaScriptQueue * m_instance = nullptr
Detailed Description
Definition at line 15 of file LuaScriptQueue.hpp.
Constructor & Destructor Documentation
LuaScriptQueue()
BARE2D::LuaScriptQueue::LuaScriptQueue () private
Definition at line 9 of file LuaScriptQueue.cpp.
Referenced by getInstance().
~LuaScriptQueue()
BARE2D::LuaScriptQueue::~LuaScriptQueue () private
Definition at line 14 of file LuaScriptQueue.cpp.
Member Function Documentation
addLuaScript() [1/2]
unsigned int BARE2D::LuaScriptQueue::addLuaScript (LuaScript & script)
Adds a script to the queue to be run.
Parameters
script A reference to the LuaScript to add to the queue.
Returns
An unsigned int which represents the UUID of the script added. This UUID will persist throughout all of the pipeline.
Definition at line 31 of file LuaScriptQueue.cpp.
References BARE2D::LuaScript::LuaScript(), m_lastUUID, and m_scripts.
Referenced by addLuaScript().
addLuaScript() [2/2]
unsigned int BARE2D::LuaScriptQueue::addLuaScript (std::string script)
Adds a script to the queue to be run by its source code.
Parameters
script The code to run.
Returns
An unsigned int which represents the UUID of the script added. This UUID will persist throughout all of the pipeline
Definition at line 42 of file LuaScriptQueue.cpp.
References addLuaScript(), BARE2D::LuaScript::inited, and BARE2D::LuaScript::m_script.
clearQueue()
void BARE2D::LuaScriptQueue::clearQueue ()
Clears the stored script queue - for regular use by tbe Script Engine. Deallocates memory that was in use in the m_scripts map.
Definition at line 56 of file LuaScriptQueue.cpp.
References m_scripts.
Referenced by BARE2D::LuaScriptEngine::update().
destroyInstance()
void BARE2D::LuaScriptQueue::destroyInstance () static
Destroys the singleton.
Definition at line 27 of file LuaScriptQueue.cpp.
References m_instance.
getInstance()
LuaScriptQueue * BARE2D::LuaScriptQueue::getInstance () static
Returns a pointer to the singleton object - creates the object if one doesn't already exist.
Returns
A pointer to the LuaScriptQueue.
Definition at line 19 of file LuaScriptQueue.cpp.
References LuaScriptQueue(), and m_instance.
Referenced by BARE2D::LuaScriptEngine::update().
getQueue()
std::map< unsigned int, LuaScript * > & BARE2D::LuaScriptQueue::getQueue ()
Returns the queue of scripts to activate.
Returns
A reference to m_scripts.
Definition at line 51 of file LuaScriptQueue.cpp.
References m_scripts.
Referenced by BARE2D::LuaScriptEngine::update().
Field Documentation
m_instance
LuaScriptQueue * BARE2D::LuaScriptQueue::m_instance = nullptr static private
Definition at line 58 of file LuaScriptQueue.hpp.
Referenced by destroyInstance(), and getInstance().
m_lastUUID
unsigned int BARE2D::LuaScriptQueue::m_lastUUID = -1 private
Definition at line 64 of file LuaScriptQueue.hpp.
Referenced by addLuaScript().
m_scripts
std::map<unsigned int, LuaScript*> BARE2D::LuaScriptQueue::m_scripts private
Definition at line 61 of file LuaScriptQueue.hpp.
Referenced by addLuaScript(), clearQueue(), and getQueue().
The documentation for this class was generated from the following files:
Source/LuaScriptQueue.hpp
Source/LuaScriptQueue.cpp