BARE2D: BARE2D::ScreenList Class Reference
BARE2D::ScreenList Class Reference
Holds and connects all of the screens used in the program in a list. Keeps track of the previous screen. Contains functions to move to the next or previous screens.
#include <ScreenList.hpp>
Public Member Functions
ScreenList ()
~ScreenList ()
Destroys the screen list, "taking care" of the screen pointers it owns.
void addScreen (Screen *screen)
Adds a screen to the list of screens, AKA the screen list. Requires non-nullptr. Also, calls the screen's initScreen function.
void addEntryScreen (Screen *screen)
Adds a screen, and sets the current screen to this one.
void moveToNextScreen ()
Moves to the next screen, updates needed variables. Also, exits old screen and enters new one.
void moveToPreviousScreen ()
Moves to the previous screen. Similar to moveToNextScreen, in that it makes sure everything's good!
Screen * getCurrentScreen ()
Private Attributes
std::vector< Screen * > m_screens
Screen * m_previousScreen = nullptr
Screen * m_currentScreen = nullptr
Detailed Description
Holds and connects all of the screens used in the program in a list. Keeps track of the previous screen. Contains functions to move to the next or previous screens.
Definition at line 13 of file ScreenList.hpp.
Constructor & Destructor Documentation
ScreenList()
BARE2D::ScreenList::ScreenList ()
Definition at line 7 of file ScreenList.cpp.
~ScreenList()
BARE2D::ScreenList::~ScreenList ()
Destroys the screen list, "taking care" of the screen pointers it owns.
Parameters
screen
Definition at line 11 of file ScreenList.cpp.
References m_currentScreen, m_previousScreen, and m_screens.
Member Function Documentation
addEntryScreen()
void BARE2D::ScreenList::addEntryScreen (Screen * screen)
Adds a screen, and sets the current screen to this one.
Parameters
screen A pointer to the entry screen.
Definition at line 27 of file ScreenList.cpp.
References addScreen(), and m_currentScreen.
addScreen()
void BARE2D::ScreenList::addScreen (Screen * screen)
Adds a screen to the list of screens, AKA the screen list. Requires non-nullptr. Also, calls the screen's initScreen function.
Parameters
screen A pointer to the screen to be added.
Definition at line 21 of file ScreenList.cpp.
References BARE2D::Screen::initScreen(), and m_screens.
Referenced by addEntryScreen().
getCurrentScreen()
Screen * BARE2D::ScreenList::getCurrentScreen ()
Returns
The current screen.
Definition at line 69 of file ScreenList.cpp.
References m_currentScreen.
moveToNextScreen()
void BARE2D::ScreenList::moveToNextScreen ()
Moves to the next screen, updates needed variables. Also, exits old screen and enters new one.
Definition at line 33 of file ScreenList.cpp.
References BARE2D::Screen::getNextScreenIndex(), m_currentScreen, m_screens, BARE2D::Screen::onEntry(), and BARE2D::Screen::onExit().
moveToPreviousScreen()
void BARE2D::ScreenList::moveToPreviousScreen ()
Moves to the previous screen. Similar to moveToNextScreen, in that it makes sure everything's good!
Definition at line 50 of file ScreenList.cpp.
References m_currentScreen, m_previousScreen, BARE2D::Screen::onEntry(), and BARE2D::Screen::onExit().
Field Documentation
m_currentScreen
Screen* BARE2D::ScreenList::m_currentScreen = nullptr private
Definition at line 54 of file ScreenList.hpp.
Referenced by addEntryScreen(), getCurrentScreen(), moveToNextScreen(), moveToPreviousScreen(), and ~ScreenList().
m_previousScreen
Screen* BARE2D::ScreenList::m_previousScreen = nullptr private
Definition at line 53 of file ScreenList.hpp.
Referenced by moveToPreviousScreen(), and ~ScreenList().
m_screens
std::vector<Screen*> BARE2D::ScreenList::m_screens private
Definition at line 52 of file ScreenList.hpp.
Referenced by addScreen(), moveToNextScreen(), and ~ScreenList().
The documentation for this class was generated from the following files:
Source/ScreenList.hpp
Source/ScreenList.cpp