BARE2D: BARE2D::Attribute< T > Class Template Reference
BARE2D::Attribute< T > Class Template Reference
#include <XMLDataTypes.hpp>
Public Member Functions
Attribute ()
Attribute (std::string Name, AttributeType Type, T *data)
~Attribute ()
void setData (T data)
Sets the actual value of the data pointer, not the address.
void swapDataPointer (T *newPtr)
Changes the old value of newPtr to that of this class' data, then changes this class' data pointer to newPtr.
T getData ()
T * getDataPointer ()
virtual std::string getDataString () override
Creates a string for XML writing of the data.
std::string getDataString ()
std::string getDataString ()
std::string getDataString ()
std::string getDataString ()
std::string getDataString ()
std::string getDataString ()
std::string getDataString ()
std::string getDataString ()
std::string getDataString ()
std::string getDataString ()
std::string getDataString ()
std::string getDataString ()
std::string getDataString ()
std::string getDataString ()
std::string getDataString ()
std::string getDataString ()
std::string getDataString ()
std::string getDataString ()
std::string getDataString ()
std::string getDataString ()
std::string getDataString ()
std::string getDataString ()
std::string getDataString ()
std::string getDataString ()
Public Member Functions inherited from BARE2D::AttributeBase
template<typename T >
void setData (T data)
template<typename T >
T getData ()
template<typename T >
T * getDataPointer ()
template<typename T >
void swapDataPointer (T *newPtr)
virtual ~AttributeBase ()
Private Member Functions
virtual void setDefaultData () override
Sets the data to its format's equivalent to 0.
void setDefaultData ()
void setDefaultData ()
void setDefaultData ()
void setDefaultData ()
void setDefaultData ()
void setDefaultData ()
void setDefaultData ()
void setDefaultData ()
void setDefaultData ()
void setDefaultData ()
void setDefaultData ()
void setDefaultData ()
void setDefaultData ()
void setDefaultData ()
void setDefaultData ()
void setDefaultData ()
void setDefaultData ()
void setDefaultData ()
void setDefaultData ()
void setDefaultData ()
void setDefaultData ()
void setDefaultData ()
void setDefaultData ()
void setDefaultData ()
Private Attributes
T * m_data = nullptr
Friends
class XMLData
Additional Inherited Members
Public Attributes inherited from BARE2D::AttributeBase
std::string name
AttributeType type
Detailed Description
template<typename T>
class BARE2D::Attribute< T >
Definition at line 54 of file XMLDataTypes.hpp.
Constructor & Destructor Documentation
Attribute() [1/2]
template<typename T > BARE2D::Attribute< T >::Attribute () inline
Definition at line 58 of file XMLDataTypes.hpp.
Attribute() [2/2]
template<typename T > BARE2D::Attribute< T >::Attribute (std::string Name, AttributeType Type, T * data)
Definition at line 13 of file XMLDataTypes.tcc.
References BARE2D::Attribute< T >::m_data, BARE2D::AttributeBase::name, and BARE2D::AttributeBase::type.
~Attribute()
template<typename T > BARE2D::Attribute< T >::~Attribute () inline
Definition at line 60 of file XMLDataTypes.hpp.
Member Function Documentation
getData()
template<typename T > T BARE2D::Attribute< T >::getData
Returns
The data
Definition at line 33 of file XMLDataTypes.tcc.
References BARE2D::Attribute< T >::m_data.
getDataPointer()
template<typename T > T * BARE2D::Attribute< T >::getDataPointer
Returns
A pointer to the data.
Definition at line 38 of file XMLDataTypes.tcc.
References BARE2D::Attribute< T >::m_data.
getDataString() [1/25]
std::string BARE2D::Attribute< std::string >::getDataString () virtual
Implements BARE2D::AttributeBase.
Definition at line 33 of file XMLDataTypes.cpp.
getDataString() [2/25]
std::string BARE2D::Attribute< unsigned int >::getDataString () virtual
Implements BARE2D::AttributeBase.
Definition at line 37 of file XMLDataTypes.cpp.
getDataString() [3/25]
std::string BARE2D::Attribute< int >::getDataString () virtual
Implements BARE2D::AttributeBase.
Definition at line 41 of file XMLDataTypes.cpp.
getDataString() [4/25]
std::string BARE2D::Attribute< float >::getDataString () virtual
Implements BARE2D::AttributeBase.
Definition at line 45 of file XMLDataTypes.cpp.
getDataString() [5/25]
std::string BARE2D::Attribute< std::string >::getDataString () virtual
Implements BARE2D::AttributeBase.
getDataString() [6/25]
std::string BARE2D::Attribute< unsigned int >::getDataString () virtual
Implements BARE2D::AttributeBase.
getDataString() [7/25]
std::string BARE2D::Attribute< bool >::getDataString () virtual
Implements BARE2D::AttributeBase.
Definition at line 49 of file XMLDataTypes.cpp.
getDataString() [8/25]
std::string BARE2D::Attribute< int >::getDataString () virtual
Implements BARE2D::AttributeBase.
getDataString() [9/25]
std::string BARE2D::Attribute< float >::getDataString () virtual
Implements BARE2D::AttributeBase.
getDataString() [10/25]
std::string BARE2D::Attribute< glm::vec2 >::getDataString () virtual
Implements BARE2D::AttributeBase.
Definition at line 53 of file XMLDataTypes.cpp.
getDataString() [11/25]
std::string BARE2D::Attribute< bool >::getDataString () virtual
Implements BARE2D::AttributeBase.
getDataString() [12/25]
std::string BARE2D::Attribute< glm::vec2 >::getDataString () virtual
Implements BARE2D::AttributeBase.
getDataString() [13/25]
std::string BARE2D::Attribute< std::vector< std::string > >::getDataString () virtual
Implements BARE2D::AttributeBase.
getDataString() [14/25]
std::string BARE2D::Attribute< std::vector< std::string > >::getDataString () virtual
Implements BARE2D::AttributeBase.
Definition at line 58 of file XMLDataTypes.cpp.
getDataString() [15/25]
std::string BARE2D::Attribute< std::vector< unsigned int > >::getDataString () virtual
Implements BARE2D::AttributeBase.
getDataString() [16/25]
std::string BARE2D::Attribute< std::vector< int > >::getDataString () virtual
Implements BARE2D::AttributeBase.
getDataString() [17/25]
std::string BARE2D::Attribute< std::vector< float > >::getDataString () virtual
Implements BARE2D::AttributeBase.
getDataString() [18/25]
std::string BARE2D::Attribute< std::vector< bool > >::getDataString () virtual
Implements BARE2D::AttributeBase.
getDataString() [19/25]
std::string BARE2D::Attribute< std::vector< unsigned int > >::getDataString () virtual
Implements BARE2D::AttributeBase.
Definition at line 66 of file XMLDataTypes.cpp.
getDataString() [20/25]
std::string BARE2D::Attribute< std::vector< glm::vec2 > >::getDataString () virtual
Implements BARE2D::AttributeBase.
getDataString() [21/25]
std::string BARE2D::Attribute< std::vector< int > >::getDataString () virtual
Implements BARE2D::AttributeBase.
Definition at line 74 of file XMLDataTypes.cpp.
getDataString() [22/25]
std::string BARE2D::Attribute< std::vector< float > >::getDataString () virtual
Implements BARE2D::AttributeBase.
Definition at line 82 of file XMLDataTypes.cpp.
getDataString() [23/25]
std::string BARE2D::Attribute< std::vector< bool > >::getDataString () virtual
Implements BARE2D::AttributeBase.
Definition at line 90 of file XMLDataTypes.cpp.
getDataString() [24/25]
std::string BARE2D::Attribute< std::vector< glm::vec2 > >::getDataString () virtual
Implements BARE2D::AttributeBase.
Definition at line 98 of file XMLDataTypes.cpp.
getDataString() [25/25]
template<typename T > virtual std::string BARE2D::Attribute< T >::getDataString () override virtual
Creates a string for XML writing of the data.
Returns
A writable string.
Implements BARE2D::AttributeBase.
setData()
template<typename T > void BARE2D::Attribute< T >::setData (T data)
Sets the actual value of the data pointer, not the address.
Parameters
data The data to set it to.
Definition at line 21 of file XMLDataTypes.tcc.
References BARE2D::Attribute< T >::m_data, BARE2D::throwFatalError(), and BARE2D::XML_FAILURE.
Referenced by BARE2D::Attribute< T >::setDefaultData().
setDefaultData() [1/25]
void BARE2D::Attribute< std::string >::setDefaultData () private virtual
Implements BARE2D::AttributeBase.
setDefaultData() [2/25]
void BARE2D::Attribute< unsigned int >::setDefaultData () private virtual
Implements BARE2D::AttributeBase.
setDefaultData() [3/25]
void BARE2D::Attribute< int >::setDefaultData () private virtual
Implements BARE2D::AttributeBase.
setDefaultData() [4/25]
void BARE2D::Attribute< float >::setDefaultData () private virtual
Implements BARE2D::AttributeBase.
setDefaultData() [5/25]
void BARE2D::Attribute< bool >::setDefaultData () private virtual
Implements BARE2D::AttributeBase.
setDefaultData() [6/25]
void BARE2D::Attribute< glm::vec2 >::setDefaultData () private virtual
Implements BARE2D::AttributeBase.
setDefaultData() [7/25]
void BARE2D::Attribute< std::vector< std::string > >::setDefaultData () private virtual
Implements BARE2D::AttributeBase.
setDefaultData() [8/25]
void BARE2D::Attribute< std::vector< unsigned int > >::setDefaultData () private virtual
Implements BARE2D::AttributeBase.
setDefaultData() [9/25]
void BARE2D::Attribute< std::vector< int > >::setDefaultData () private virtual
Implements BARE2D::AttributeBase.
setDefaultData() [10/25]
void BARE2D::Attribute< std::vector< float > >::setDefaultData () private virtual
Implements BARE2D::AttributeBase.
setDefaultData() [11/25]
void BARE2D::Attribute< std::vector< bool > >::setDefaultData () private virtual
Implements BARE2D::AttributeBase.
setDefaultData() [12/25]
void BARE2D::Attribute< std::vector< glm::vec2 > >::setDefaultData () private virtual
Implements BARE2D::AttributeBase.
setDefaultData() [13/25]
void BARE2D::Attribute< std::string >::setDefaultData () private virtual
Implements BARE2D::AttributeBase.
Definition at line 108 of file XMLDataTypes.cpp.
References BARE2D::Attribute< T >::setData().
setDefaultData() [14/25]
void BARE2D::Attribute< unsigned int >::setDefaultData () private virtual
Implements BARE2D::AttributeBase.
Definition at line 112 of file XMLDataTypes.cpp.
References BARE2D::Attribute< T >::setData().
setDefaultData() [15/25]
void BARE2D::Attribute< int >::setDefaultData () private virtual
Implements BARE2D::AttributeBase.
Definition at line 116 of file XMLDataTypes.cpp.
References BARE2D::Attribute< T >::setData().
setDefaultData() [16/25]
void BARE2D::Attribute< float >::setDefaultData () private virtual
Implements BARE2D::AttributeBase.
Definition at line 120 of file XMLDataTypes.cpp.
References BARE2D::Attribute< T >::setData().
setDefaultData() [17/25]
void BARE2D::Attribute< bool >::setDefaultData () private virtual
Implements BARE2D::AttributeBase.
Definition at line 124 of file XMLDataTypes.cpp.
References BARE2D::Attribute< T >::setData().
setDefaultData() [18/25]
void BARE2D::Attribute< glm::vec2 >::setDefaultData () private virtual
Implements BARE2D::AttributeBase.
Definition at line 128 of file XMLDataTypes.cpp.
References BARE2D::Attribute< T >::setData().
setDefaultData() [19/25]
void BARE2D::Attribute< std::vector< std::string > >::setDefaultData () private virtual
Implements BARE2D::AttributeBase.
Definition at line 132 of file XMLDataTypes.cpp.
References BARE2D::Attribute< T >::setData().
setDefaultData() [20/25]
void BARE2D::Attribute< std::vector< unsigned int > >::setDefaultData () private virtual
Implements BARE2D::AttributeBase.
Definition at line 136 of file XMLDataTypes.cpp.
References BARE2D::Attribute< T >::setData().
setDefaultData() [21/25]
void BARE2D::Attribute< std::vector< int > >::setDefaultData () private virtual
Implements BARE2D::AttributeBase.
Definition at line 140 of file XMLDataTypes.cpp.
References BARE2D::Attribute< T >::setData().
setDefaultData() [22/25]
void BARE2D::Attribute< std::vector< float > >::setDefaultData () private virtual
Implements BARE2D::AttributeBase.
Definition at line 144 of file XMLDataTypes.cpp.
References BARE2D::Attribute< T >::setData().
setDefaultData() [23/25]
void BARE2D::Attribute< std::vector< bool > >::setDefaultData () private virtual
Implements BARE2D::AttributeBase.
Definition at line 148 of file XMLDataTypes.cpp.
References BARE2D::Attribute< T >::setData().
setDefaultData() [24/25]
void BARE2D::Attribute< std::vector< glm::vec2 > >::setDefaultData () private virtual
Implements BARE2D::AttributeBase.
Definition at line 152 of file XMLDataTypes.cpp.
References BARE2D::Attribute< T >::setData().
setDefaultData() [25/25]
template<typename T > virtual void BARE2D::Attribute< T >::setDefaultData () override private virtual
Sets the data to its format's equivalent to 0.
Implements BARE2D::AttributeBase.
swapDataPointer()
template<typename T > void BARE2D::Attribute< T >::swapDataPointer (T * newPtr)
Changes the old value of newPtr to that of this class' data, then changes this class' data pointer to newPtr.
Parameters
newPtr
Definition at line 27 of file XMLDataTypes.tcc.
References BARE2D::Attribute< T >::m_data.
Friends And Related Function Documentation
XMLData
template<typename T > friend class XMLData friend
Definition at line 55 of file XMLDataTypes.hpp.
Member Data Documentation
m_data
template<typename T > T* BARE2D::Attribute< T >::m_data = nullptr private
Definition at line 90 of file XMLDataTypes.hpp.
Referenced by BARE2D::Attribute< T >::Attribute(), BARE2D::Attribute< T >::getData(), BARE2D::Attribute< T >::getDataPointer(), BARE2D::Attribute< T >::setData(), and BARE2D::Attribute< T >::swapDataPointer().
The documentation for this class was generated from the following files:
Source/XMLDataTypes.hpp
Source/XMLDataTypes.tcc