BARE2D: BARE2D::LuaScriptContextWrapper Class Reference
BARE2D::LuaScriptContextWrapper Class Reference
#include <LuaScript.hpp>
Public Member Functions
LuaScriptContextWrapper ()
~LuaScriptContextWrapper ()
void init (lua_State *parentState, LuaScript *script)
Creates and initializes all the necessary bits.
void destroy ()
Cleans up.
void start ()
Starts the script.
void update ()
Updates the script - decreases delay counter, checks if it is finished, etc.
bool isCompleted ()
Returns m_completed.
Protected Member Functions
void loadLua (std::string &luaStr)
Loads and compiles the given Lua script. Also, sets m_scriptReference to the index of the compiled script in the registry.
void createThread ()
Creates the m_state variable as a thread, or subroutine of the parent.
Protected Attributes
lua_State * m_state = nullptr
lua_State * m_parent = nullptr
bool m_yielded = false
unsigned int m_remainingDelay = 0
bool m_completed = false
int m_scriptReference = LUA_REFNIL
int m_threadReference = LUA_REFNIL
Detailed Description
Definition at line 29 of file LuaScript.hpp.
Constructor & Destructor Documentation
LuaScriptContextWrapper()
BARE2D::LuaScriptContextWrapper::LuaScriptContextWrapper ()
Definition at line 15 of file LuaScript.cpp.
Referenced by BARE2D::LuaScriptEngine::createLuaContext().
~LuaScriptContextWrapper()
BARE2D::LuaScriptContextWrapper::~LuaScriptContextWrapper ()
Definition at line 19 of file LuaScript.cpp.
Member Function Documentation
createThread()
void BARE2D::LuaScriptContextWrapper::createThread () protected
Creates the m_state variable as a thread, or subroutine of the parent.
Definition at line 36 of file LuaScript.cpp.
References BARE2D::LUA_FAILURE, m_parent, m_state, m_threadReference, and BARE2D::throwError().
Referenced by init().
destroy()
void BARE2D::LuaScriptContextWrapper::destroy ()
Cleans up.
Definition at line 49 of file LuaScript.cpp.
References m_completed, and m_state.
Referenced by BARE2D::LuaContextManager::update(), and update().
init()
void BARE2D::LuaScriptContextWrapper::init (lua_State * parentState, LuaScript * script)
Creates and initializes all the necessary bits.
Parameters
id The ID of the script, which was assigned from the LuaScriptQueue
parentState The masterstate, generally, although I suppose it could be others.
Definition at line 24 of file LuaScript.cpp.
References createThread(), loadLua(), m_parent, and BARE2D::LuaScript::m_script.
Referenced by BARE2D::LuaScriptEngine::createLuaContext().
isCompleted()
bool BARE2D::LuaScriptContextWrapper::isCompleted ()
Returns m_completed.
Definition at line 143 of file LuaScript.cpp.
References m_completed.
Referenced by BARE2D::LuaContextManager::update().
loadLua()
void BARE2D::LuaScriptContextWrapper::loadLua (std::string & luaStr) protected
Loads and compiles the given Lua script. Also, sets m_scriptReference to the index of the compiled script in the registry.
Parameters
luaStr The script to compile.
Definition at line 124 of file LuaScript.cpp.
References BARE2D::LUA_FAILURE, m_scriptReference, m_state, and BARE2D::throwError().
Referenced by init().
start()
void BARE2D::LuaScriptContextWrapper::start ()
Starts the script.
Definition at line 60 of file LuaScript.cpp.
References BARE2D::LUA_FAILURE, m_scriptReference, m_state, and BARE2D::throwError().
Referenced by BARE2D::LuaScriptEngine::update().
update()
void BARE2D::LuaScriptContextWrapper::update ()
Updates the script - decreases delay counter, checks if it is finished, etc.
Definition at line 83 of file LuaScript.cpp.
References destroy(), BARE2D::LUA_FAILURE, m_completed, m_remainingDelay, m_state, m_yielded, and BARE2D::throwError().
Referenced by BARE2D::LuaContextManager::update().
Member Data Documentation
m_completed
bool BARE2D::LuaScriptContextWrapper::m_completed = false protected
Definition at line 83 of file LuaScript.hpp.
Referenced by destroy(), isCompleted(), and update().
m_parent
lua_State* BARE2D::LuaScriptContextWrapper::m_parent = nullptr protected
Definition at line 76 of file LuaScript.hpp.
Referenced by createThread(), and init().
m_remainingDelay
unsigned int BARE2D::LuaScriptContextWrapper::m_remainingDelay = 0 protected
Definition at line 80 of file LuaScript.hpp.
Referenced by update().
m_scriptReference
int BARE2D::LuaScriptContextWrapper::m_scriptReference = LUA_REFNIL protected
Definition at line 86 of file LuaScript.hpp.
Referenced by loadLua(), and start().
m_state
lua_State* BARE2D::LuaScriptContextWrapper::m_state = nullptr protected
Definition at line 74 of file LuaScript.hpp.
Referenced by createThread(), destroy(), loadLua(), start(), and update().
m_threadReference
int BARE2D::LuaScriptContextWrapper::m_threadReference = LUA_REFNIL protected
Definition at line 88 of file LuaScript.hpp.
Referenced by createThread().
m_yielded
bool BARE2D::LuaScriptContextWrapper::m_yielded = false protected
Definition at line 79 of file LuaScript.hpp.
Referenced by update().
The documentation for this class was generated from the following files:
Source/LuaScript.hpp
Source/LuaScript.cpp