BARE2D: BARE2D::BasicRenderer Class Reference
BARE2D::BasicRenderer Class Reference
#include <BasicRenderer.hpp>
Public Member Functions
BasicRenderer (std::string &fragShader, std::string &vertShader, unsigned int perspectiveWidth=2, unsigned int perspectiveHeight=2)
virtual ~BasicRenderer ()
virtual void init () override
Initializes all necessary bits of the renderer.
virtual void preRender () override
Does stuff inside of the render function, within the shader's use.
virtual void setCamera (std::shared_ptr< Camera2D > camera)
Sets the camera to a given pointer. This means that the renderer takes ownership.
std::shared_ptr< Camera2D > getCamera ()
virtual void draw (glm::vec4 destRect, glm::vec4 uvRect, GLuint texture, float depth, Colour colour=Colour(255, 255, 255, 255), float angle=0.0f, glm::vec2 COR=glm::vec2(0.5f))
Public Member Functions inherited from BARE2D::Renderer
Renderer ()
virtual ~Renderer ()
virtual void begin ()
Clears the necessary vectors, etc. to prepare for draw() calls, etc.
virtual void end ()
Creates the renderbatches, does necessary stuff before render() call.
virtual void initUniforms ()
Initializes all uniforms, such as colour attachments, depth attachments, etc.
virtual void destroy ()
Frees all necessary memory.
virtual void render ()
Actually renders the contents to the screen!
ShaderProgram * getShader ()
Protected Member Functions
virtual void createRenderBatches () override
Constructs all of the render batches from data given by, say, draw() calls.
Protected Attributes
std::string m_fragShader
std::string m_vertShader
std::vector< Glyph * > m_glyphs
std::shared_ptr< Camera2D > m_camera
Protected Attributes inherited from BARE2D::Renderer
ShaderProgram m_shader
VAO m_vertexArrayObject
std::vector< RenderBatch > m_batches
Detailed Description
Definition at line 11 of file BasicRenderer.hpp.
Constructor & Destructor Documentation
BasicRenderer()
BARE2D::BasicRenderer::BasicRenderer (std::string & fragShader, std::string & vertShader, unsigned int perspectiveWidth = 2, unsigned int perspectiveHeight = 2)
Definition at line 5 of file BasicRenderer.cpp.
References BARE2D::Camera2D::init(), m_camera, m_fragShader, m_vertShader, and BARE2D::Renderer::Renderer().
Referenced by BARE2D::BumpyRenderer::BumpyRenderer(), and BARE2D::FontRenderer::FontRenderer().
~BasicRenderer()
BARE2D::BasicRenderer::~BasicRenderer () virtual
Definition at line 10 of file BasicRenderer.cpp.
Member Function Documentation
createRenderBatches()
void BARE2D::BasicRenderer::createRenderBatches () override protected virtual
Constructs all of the render batches from data given by, say, draw() calls.
Implements BARE2D::Renderer.
Reimplemented in BARE2D::BumpyRenderer.
Definition at line 55 of file BasicRenderer.cpp.
References BARE2D::VAO::bindVBO(), BARE2D::Glyph::bottomLeft, BARE2D::Glyph::bottomRight, BARE2D::Renderer::m_batches, m_glyphs, BARE2D::Renderer::m_vertexArrayObject, RenderBatch::numVertices, BARE2D::Glyph::texture, BARE2D::Glyph::topLeft, BARE2D::Glyph::topRight, and BARE2D::VAO::unbindVBO().
draw()
void BARE2D::BasicRenderer::draw (glm::vec4 destRect, glm::vec4 uvRect, GLuint texture, float depth, Colour colour = Colour(255, 255, 255, 255), float angle = 0.0f, glm::vec2 COR = glm::vec2(0.5f)) virtual
Reimplemented in BARE2D::BumpyRenderer.
Definition at line 44 of file BasicRenderer.cpp.
References BARE2D::Glyph::Glyph(), BARE2D::Camera2D::isRectInScene(), m_camera, and m_glyphs.
Referenced by BARE2D::FontRenderer::draw().
getCamera()
std::shared_ptr< Camera2D > BARE2D::BasicRenderer::getCamera ()
Returns
Returns the Camera pointer. To be used only to link multiple renderers' cameras.
Definition at line 29 of file BasicRenderer.cpp.
References m_camera.
init()
void BARE2D::BasicRenderer::init () override virtual
Initializes all necessary bits of the renderer.
Reimplemented from BARE2D::Renderer.
Definition at line 13 of file BasicRenderer.cpp.
References BARE2D::VAO::addVertexAttribute(), BARE2D::Vertex::colour, BARE2D::ShaderProgram::compileShaders(), BARE2D::Renderer::init(), BARE2D::ShaderProgram::linkShaders(), m_fragShader, BARE2D::Renderer::m_shader, BARE2D::Renderer::m_vertexArrayObject, m_vertShader, BARE2D::Vertex::position, and BARE2D::Vertex::uv.
preRender()
void BARE2D::BasicRenderer::preRender () override virtual
Does stuff inside of the render function, within the shader's use.
Reimplemented from BARE2D::Renderer.
Reimplemented in BARE2D::BumpyRenderer.
Definition at line 33 of file BasicRenderer.cpp.
References BARE2D::Camera2D::getCameraMatrix(), m_camera, BARE2D::Renderer::m_shader, BARE2D::ShaderProgram::setUniform(), BARE2D::ShaderProgram::setUniformMatrix(), and BARE2D::Camera2D::update().
setCamera()
void BARE2D::BasicRenderer::setCamera (std::shared_ptr< Camera2D > camera) virtual
Sets the camera to a given pointer. This means that the renderer takes ownership.
Parameters
camera The pointer to the camera.
Definition at line 25 of file BasicRenderer.cpp.
References m_camera.
Member Data Documentation
m_camera
std::shared_ptr<Camera2D> BARE2D::BasicRenderer::m_camera protected
Definition at line 40 of file BasicRenderer.hpp.
Referenced by BasicRenderer(), draw(), BARE2D::BumpyRenderer::draw(), getCamera(), preRender(), BARE2D::BumpyRenderer::preRender(), and setCamera().
m_fragShader
std::string BARE2D::BasicRenderer::m_fragShader protected
Definition at line 36 of file BasicRenderer.hpp.
Referenced by BasicRenderer(), and init().
m_glyphs
std::vector<Glyph*> BARE2D::BasicRenderer::m_glyphs protected
Definition at line 38 of file BasicRenderer.hpp.
Referenced by createRenderBatches(), BARE2D::BumpyRenderer::createRenderBatches(), draw(), and BARE2D::BumpyRenderer::draw().
m_vertShader
std::string BARE2D::BasicRenderer::m_vertShader protected
Definition at line 36 of file BasicRenderer.hpp.
Referenced by BasicRenderer(), and init().
The documentation for this class was generated from the following files:
Source/BasicRenderer.hpp
Source/BasicRenderer.cpp