BARE2D: BARE2D::Window Class Reference
BARE2D::Window Class Reference
It's a graphical window, holds the contexts for GL and SDL.
#include <Window.hpp>
Public Member Functions
Window ()
~Window ()
void create (unsigned int flags)
This is a graphical window. It holds information about the GL context, as well as the SDL window context. Takes some flags on creation (SDL_WindowFlags):
void setTitle (std::string newTitle)
Sets the title of the window.
void setSize (unsigned int width, unsigned int height)
Sets the size of the window (defaults to 600x400)
void swapBuffer ()
Swaps the buffer of the SDL window - used to draw to one while the other displays, so no flickering is seen.
unsigned int getWidth () const
Returns the width of the window.
unsigned int getHeight () const
Returns the height of the window.
Private Attributes
SDL_Window * m_SDLWindow = nullptr
SDL_GLContext m_GLContext = nullptr
unsigned int m_width = 600
unsigned int m_height = 400
std::string m_title = "BARE2D Window"
Detailed Description
It's a graphical window, holds the contexts for GL and SDL.
Definition at line 13 of file Window.hpp.
Constructor & Destructor Documentation
Window()
BARE2D::Window::Window ()
Definition at line 9 of file Window.cpp.
Referenced by BARE2D::App::init().
~Window()
BARE2D::Window::~Window ()
Definition at line 13 of file Window.cpp.
Member Function Documentation
create()
void BARE2D::Window::create (unsigned int flags)
This is a graphical window. It holds information about the GL context, as well as the SDL window context. Takes some flags on creation (SDL_WindowFlags):
SDL_WINDOW_FULLSCREEN
FULLSCREN_DESKTOP
OPENGL
VULKAN
SHOWN
HIDDEN
BORDERLESS
RESIZABLE
MIN/MAXIMIZED
INPUT_GRABBED
INPUT_FOCUS
MOUSE_FOCUS
FOREIGN
ALLOW_HIGHDPI
MOUSE_CAPTURE
ALWAYS_ON_TOP
SKIP_TASKBAR
UTILITY
TOOLTIP
POPUP_MENU These can be ORed together to transfer them to this function
Returns
Returns an error (if one is created)
Definition at line 20 of file Window.cpp.
Referenced by BARE2D::App::init().
getHeight()
unsigned int BARE2D::Window::getHeight () const
Returns the height of the window.
Definition at line 97 of file Window.cpp.
Referenced by BARE2D::App::draw().
getWidth()
unsigned int BARE2D::Window::getWidth () const
Returns the width of the window.
Definition at line 93 of file Window.cpp.
Referenced by BARE2D::App::draw().
setSize()
void BARE2D::Window::setSize (unsigned int width, unsigned int height)
Sets the size of the window (defaults to 600x400)
Parameters
width
height
Definition at line 77 of file Window.cpp.
setTitle()
void BARE2D::Window::setTitle (std::string newTitle)
Sets the title of the window.
Parameters
newTitle The new title to be set!
Definition at line 72 of file Window.cpp.
swapBuffer()
void BARE2D::Window::swapBuffer ()
Swaps the buffer of the SDL window - used to draw to one while the other displays, so no flickering is seen.
Definition at line 89 of file Window.cpp.
Referenced by BARE2D::App::run().
Member Data Documentation
m_GLContext
SDL_GLContext BARE2D::Window::m_GLContext = nullptr private
Definition at line 76 of file Window.hpp.
m_height
unsigned int BARE2D::Window::m_height = 400 private
Definition at line 78 of file Window.hpp.
m_SDLWindow
SDL_Window* BARE2D::Window::m_SDLWindow = nullptr private
Definition at line 75 of file Window.hpp.
m_title
std::string BARE2D::Window::m_title = "BARE2D Window" private
Definition at line 79 of file Window.hpp.
m_width
unsigned int BARE2D::Window::m_width = 600 private
Definition at line 78 of file Window.hpp.
The documentation for this class was generated from the following files:
Source/Window.hpp
Source/Window.cpp