BARE2D: BARE2D::Cache< S, T > Class Template Reference
BARE2D::Cache< S, T > Class Template Reference
This is a skeleton cache class. This can only be used by the ResourceManager or other classes who actually maintain proper pointer ownership.
#include <Cache.hpp>
Public Member Functions
Cache ()
T * findItem (S &key)
Finds an item based on a key.
T * operator[] (S &key)
An operator overload that returns the object stored at key. Analagous to findItem();.
bool addItem (S &key, T *item)
Simply adds an item.
bool setItem (S &key, T *item)
Adds or overwrites an item.
T * createItem (S &key, std::function< T *()> creationFunc=[]() -> T *{ return new T();})
Creates an item with a given key and uses the constructor to fill out the rest. If it already exists, overwrite it and return that pointer.
void clear ()
Clears the cache. Destroys all data, calling their respective destructors, then delete.
unsigned int getCount ()
Returns the number of items in the cache.
std::unordered_map< S, T * >::iterator begin ()
std::unordered_map< S, T * >::iterator end ()
bool operator!= (Cache &other)
Private Attributes
std::unordered_map< S, T * > m_data
Detailed Description
template<typename S, typename T>
class BARE2D::Cache< S, T >
This is a skeleton cache class. This can only be used by the ResourceManager or other classes who actually maintain proper pointer ownership.
Definition at line 15 of file Cache.hpp.
Constructor & Destructor Documentation
Cache()
template<typename S , typename T > BARE2D::Cache< S, T >::Cache () inline
Definition at line 18 of file Cache.hpp.
Member Function Documentation
addItem()
template<typename S , typename T > bool BARE2D::Cache< S, T >::addItem (S & key, T * item)
Simply adds an item.
Parameters
key The key for the item - how it is stored
item The item itself
Returns
True if successful, false otherwise.
Definition at line 28 of file Cache_impl.tcc.
Referenced by BARE2D::XMLDataManager::addData().
begin()
template<typename S , typename T > std::unordered_map< S, T * >::iterator BARE2D::Cache< S, T >::begin
Definition at line 86 of file Cache_impl.tcc.
clear()
template<typename S , typename T > void BARE2D::Cache< S, T >::clear
Clears the cache. Destroys all data, calling their respective destructors, then delete.
Definition at line 68 of file Cache_impl.tcc.
Referenced by BARE2D::XMLDataManager::clearCache().
createItem()
template<typename S , typename T > T * BARE2D::Cache< S, T >::createItem (S & key, std::function< T *()> creationFunc = []() -> T* { return new T(); })
Creates an item with a given key and uses the constructor to fill out the rest. If it already exists, overwrite it and return that pointer.
Parameters
key The key to give the item.
creationFunc A function that allocates and returns a new object. Defaults, but it can slice data if you're using inheritance.
Returns
A pointer to that item.
Definition at line 46 of file Cache_impl.tcc.
Referenced by BARE2D::XMLDataManager::getDataCache().
end()
template<typename S , typename T > std::unordered_map< S, T * >::iterator BARE2D::Cache< S, T >::end
Definition at line 91 of file Cache_impl.tcc.
findItem()
template<typename S , typename T > T * BARE2D::Cache< S, T >::findItem (S & key)
Finds an item based on a key.
Parameters
key The key to find the item by.
Returns
A pointer to the data, or nullptr if no such data exists
Definition at line 8 of file Cache_impl.tcc.
Referenced by BARE2D::XMLDataManager::addData(), BARE2D::Cache< std::string, BARE2D::Sound >::addItem(), BARE2D::Cache< std::string, BARE2D::Sound >::createItem(), BARE2D::XMLDataManager::getData(), BARE2D::Cache< std::string, BARE2D::Sound >::operator[](), and BARE2D::Cache< std::string, BARE2D::Sound >::setItem().
getCount()
template<typename S , typename T > unsigned int BARE2D::Cache< S, T >::getCount
Returns the number of items in the cache.
Definition at line 81 of file Cache_impl.tcc.
Referenced by BARE2D::XMLDataManager::getDataCount().
operator!=()
template<typename S , typename T > bool BARE2D::Cache< S, T >::operator!= (Cache< S, T > & other)
Definition at line 96 of file Cache_impl.tcc.
operator[]()
template<typename S , typename T > T * BARE2D::Cache< S, T >::operator[] (S & key)
An operator overload that returns the object stored at key. Analagous to findItem();.
Parameters
key
Definition at line 23 of file Cache_impl.tcc.
Referenced by BARE2D::XMLDataManager::getDataCache().
setItem()
template<typename S , typename T > bool BARE2D::Cache< S, T >::setItem (S & key, T * item)
Adds or overwrites an item.
Parameters
key The key for the item - how it is stored
item The item itself
Returns
True if successful, false otherwise.
Definition at line 36 of file Cache_impl.tcc.
Referenced by BARE2D::XMLDataManager::setData().
Field Documentation
m_data
template<typename S , typename T > std::unordered_map<S, T*> BARE2D::Cache< S, T >::m_data private
Definition at line 78 of file Cache.hpp.
Referenced by BARE2D::Cache< std::string, BARE2D::Sound >::addItem(), BARE2D::Cache< std::string, BARE2D::Sound >::begin(), BARE2D::Cache< std::string, BARE2D::Sound >::clear(), BARE2D::Cache< std::string, BARE2D::Sound >::createItem(), BARE2D::Cache< std::string, BARE2D::Sound >::end(), BARE2D::Cache< std::string, BARE2D::Sound >::findItem(), BARE2D::Cache< std::string, BARE2D::Sound >::getCount(), BARE2D::Cache< std::string, BARE2D::Sound >::operator!=(), and BARE2D::Cache< std::string, BARE2D::Sound >::setItem().
The documentation for this class was generated from the following files:
Source/Cache.hpp
Source/Cache_impl.tcc