BARE2D: BARE2D::BumpyRenderer Class Reference
BARE2D::BumpyRenderer Class Reference
This is a BasicRenderer, but it includes the usage of bumpmaps. This can be useful for lighting.
#include <BumpyRenderer.hpp>
Public Member Functions
BumpyRenderer (std::string &fragShader, std::string &vertShader, unsigned int perspectiveWidth=2, unsigned int perspectiveHeight=2)
~BumpyRenderer ()
virtual void initUniforms () override
Initializes all uniforms, such as colour attachments, depth attachments, etc.
virtual void preRender () override
Does stuff inside of the render function, within the shader's use.
virtual void render () override
Actually renders the contents to the screen!
virtual void draw (glm::vec4 destRect, glm::vec4 uvRect, GLuint texture, float depth, Colour colour=Colour(255, 255, 255, 255), float angle=0.0f, glm::vec2 COR=glm::vec2(0.5f))
virtual void draw (glm::vec4 destRect, glm::vec4 uvRect, GLuint texture, GLuint bumpmap, float depth, Colour colour=Colour(255, 255, 255, 255), float angle=0.0f, glm::vec2 COR=glm::vec2(0.5f))
Public Member Functions inherited from BARE2D::BasicRenderer
BasicRenderer (std::string &fragShader, std::string &vertShader, unsigned int perspectiveWidth=2, unsigned int perspectiveHeight=2)
virtual ~BasicRenderer ()
virtual void init () override
Initializes all necessary bits of the renderer.
virtual void setCamera (std::shared_ptr< Camera2D > camera)
Sets the camera to a given pointer. This means that the renderer takes ownership.
std::shared_ptr< Camera2D > getCamera ()
Public Member Functions inherited from BARE2D::Renderer
Renderer ()
virtual ~Renderer ()
virtual void begin ()
Clears the necessary vectors, etc. to prepare for draw() calls, etc.
virtual void end ()
Creates the renderbatches, does necessary stuff before render() call.
virtual void destroy ()
Frees all necessary memory.
ShaderProgram * getShader ()
Protected Member Functions
virtual void createRenderBatches () override
Constructs all of the render batches from data given by, say, draw() calls.
Protected Member Functions inherited from BARE2D::Renderer
virtual void link (std::initializer_list< std::string > attributes)
Protected Attributes
std::vector< GLuint > m_batchBumpmaps
Protected Attributes inherited from BARE2D::BasicRenderer
std::string m_fragShader
std::string m_vertShader
std::vector< Glyph * > m_glyphs
std::shared_ptr< Camera2D > m_camera
Protected Attributes inherited from BARE2D::Renderer
ShaderProgram m_shader
VAO m_vertexArrayObject
std::vector< RenderBatch > m_batches
Detailed Description
This is a BasicRenderer, but it includes the usage of bumpmaps. This can be useful for lighting.
Definition at line 23 of file BumpyRenderer.hpp.
Constructor & Destructor Documentation
BumpyRenderer()
BARE2D::BumpyRenderer::BumpyRenderer (std::string & fragShader, std::string & vertShader, unsigned int perspectiveWidth = 2, unsigned int perspectiveHeight = 2)
Definition at line 12 of file BumpyRenderer.cpp.
References BARE2D::BasicRenderer::BasicRenderer().
~BumpyRenderer()
BARE2D::BumpyRenderer::~BumpyRenderer ()
Definition at line 16 of file BumpyRenderer.cpp.
Member Function Documentation
createRenderBatches()
void BARE2D::BumpyRenderer::createRenderBatches () override protected virtual
Constructs all of the render batches from data given by, say, draw() calls.
Reimplemented from BARE2D::BasicRenderer.
Definition at line 86 of file BumpyRenderer.cpp.
References BARE2D::VAO::bindVBO(), BARE2D::Glyph::bottomLeft, BARE2D::Glyph::bottomRight, BARE2D::BumpyGlyph::bumpmap, m_batchBumpmaps, BARE2D::Renderer::m_batches, BARE2D::BasicRenderer::m_glyphs, BARE2D::Renderer::m_vertexArrayObject, RenderBatch::numVertices, BARE2D::Glyph::texture, BARE2D::Glyph::topLeft, BARE2D::Glyph::topRight, and BARE2D::VAO::unbindVBO().
Referenced by render().
draw() [1/2]
void BARE2D::BumpyRenderer::draw (glm::vec4 destRect, glm::vec4 uvRect, GLuint texture, float depth, Colour colour = Colour(255, 255, 255, 255), float angle = 0.0f, glm::vec2 COR = glm::vec2(0.5f)) virtual
Reimplemented from BARE2D::BasicRenderer.
Definition at line 73 of file BumpyRenderer.cpp.
References BARE2D::throwFatalError(), and BARE2D::UNINITIALIZED_FUNCTION.
draw() [2/2]
void BARE2D::BumpyRenderer::draw (glm::vec4 destRect, glm::vec4 uvRect, GLuint texture, GLuint bumpmap, float depth, Colour colour = Colour(255, 255, 255, 255), float angle = 0.0f, glm::vec2 COR = glm::vec2(0.5f)) virtual
Definition at line 77 of file BumpyRenderer.cpp.
References BARE2D::BumpyGlyph::BumpyGlyph(), BARE2D::Camera2D::isRectInViewspace(), BARE2D::BasicRenderer::m_camera, and BARE2D::BasicRenderer::m_glyphs.
initUniforms()
void BARE2D::BumpyRenderer::initUniforms () override virtual
Initializes all uniforms, such as colour attachments, depth attachments, etc.
Reimplemented from BARE2D::Renderer.
Definition at line 19 of file BumpyRenderer.cpp.
References BARE2D::Renderer::m_shader, and BARE2D::ShaderProgram::setUniform().
preRender()
void BARE2D::BumpyRenderer::preRender () override virtual
Does stuff inside of the render function, within the shader's use.
Reimplemented from BARE2D::BasicRenderer.
Definition at line 27 of file BumpyRenderer.cpp.
References BARE2D::Camera2D::getCameraMatrix(), BARE2D::BasicRenderer::m_camera, BARE2D::Renderer::m_shader, BARE2D::ShaderProgram::setUniformMatrix(), and BARE2D::Camera2D::update().
Referenced by render().
render()
void BARE2D::BumpyRenderer::render () override virtual
Actually renders the contents to the screen!
Reimplemented from BARE2D::Renderer.
Definition at line 35 of file BumpyRenderer.cpp.
References BARE2D::VAO::bind(), BARE2D::GLContext::bindTexture(), createRenderBatches(), BARE2D::GLContextManager::getContext(), m_batchBumpmaps, BARE2D::Renderer::m_batches, BARE2D::Renderer::m_shader, BARE2D::Renderer::m_vertexArrayObject, RenderBatch::numVertices, RenderBatch::offset, preRender(), BARE2D::GLContext::setActiveTexture(), RenderBatch::textureID, BARE2D::VAO::unbind(), BARE2D::ShaderProgram::unuse(), and BARE2D::ShaderProgram::use().
Field Documentation
m_batchBumpmaps
std::vector<GLuint> BARE2D::BumpyRenderer::m_batchBumpmaps protected
Definition at line 43 of file BumpyRenderer.hpp.
Referenced by createRenderBatches(), and render().
The documentation for this class was generated from the following files:
Source/BumpyRenderer.hpp
Source/BumpyRenderer.cpp