BARE2D: BARE2D::LuaFunctions Namespace Reference
BARE2D::LuaFunctions Namespace Reference
Functions
int delay (lua_State *L)
A custom function which calls a lua_yield. Takes one argument, an integer representing how many updates the script should yield for.
int print (lua_State *L)
Uses the Logger to print to the screen and log. Takes one argument, a string to print.
Function Documentation
delay()
int BARE2D::LuaFunctions::delay (lua_State * L)
A custom function which calls a lua_yield. Takes one argument, an integer representing how many updates the script should yield for.
Parameters
L The state
Returns
The number of return values. Always zero.
Definition at line 9 of file LuaFunctions.cpp.
Referenced by BARE2D::LuaScriptEngine::init().
print()
int BARE2D::LuaFunctions::print (lua_State * L)
Uses the Logger to print to the screen and log. Takes one argument, a string to print.
Parameters
L The state
Returns
The number of return values. Always zero.
Definition at line 16 of file LuaFunctions.cpp.
References BARE2D::Logger::getInstance(), and BARE2D::Logger::log().
Referenced by BARE2D::LuaScriptEngine::init().