BARE2D: BARE2D::CameraState Class Reference
BARE2D::CameraState Class Reference
Holds some basic information that the camera holds in a state.
#include <Camera2D.hpp>
Public Attributes
glm::vec2 position = glm::vec2(0.0f)
glm::vec2 scale = glm::vec2(1.0f)
Detailed Description
Holds some basic information that the camera holds in a state.
Definition at line 11 of file Camera2D.hpp.
Member Data Documentation
position
glm::vec2 BARE2D::CameraState::position = glm::vec2(0.0f)
Definition at line 12 of file Camera2D.hpp.
Referenced by BARE2D::Camera2D::getPosition(), BARE2D::Camera2D::getScreenPositionFromViewedPosition(), BARE2D::Camera2D::getViewedPositionFromScreenPosition(), BARE2D::Camera2D::init(), BARE2D::Camera2D::offsetPosition(), BARE2D::Camera2D::setPosition(), and BARE2D::Camera2D::update().
scale
glm::vec2 BARE2D::CameraState::scale = glm::vec2(1.0f)
Definition at line 13 of file Camera2D.hpp.
Referenced by BARE2D::Camera2D::getScaleX(), BARE2D::Camera2D::getScaleY(), BARE2D::Camera2D::getScreenPositionFromViewedPosition(), BARE2D::Camera2D::getScreenSizeFromViewedSize(), BARE2D::Camera2D::getViewedPositionFromScreenPosition(), BARE2D::Camera2D::getViewedSizeFromScreenSize(), BARE2D::Camera2D::init(), BARE2D::Camera2D::offsetScale(), BARE2D::Camera2D::setScale(), and BARE2D::Camera2D::update().
The documentation for this class was generated from the following file:
Source/Camera2D.hpp