BARE2D: BARE2D::ShaderProgram Class Reference
BARE2D::ShaderProgram Class Reference
The ShaderProgram is a GLSL program which combines two shaders - the vertex shader and the fragment shader - to allow rendering. Each renderer should have its own program.
#include <ShaderProgram.hpp>
Public Member Functions
ShaderProgram ()
~ShaderProgram ()
void compileShaders (const char *vertexShaderPath, const char *fragmentShaderPath)
Compiles the shaders. Does not link them.
void compileShadersFromSource (const char *vertexSource, const char *fragmentSource)
Similar to compileShaders, this just compiles the shaders.
void linkShaders (std::initializer_list< std::string > attributes)
Links the compiled shaders together to create a coherent shader program.
template<class T >
void setUniform (const std::string uniform, T &data)
A generalized wrapper to find and set a uniform for this shader.
template<class T >
void setUniformMatrix (const std::string uniform, bool transpose, T &data)
Similar to setUniform.
bool doesUniformExist (const std::string uniform)
void use ()
Activates this shader program for the renderer to use.
void unuse ()
Deactivates this shader program.
void destroy ()
Releases all bound objects and deletes any allocated stuff.
template<>
void setUniform (const std::string uniform, int &data)
template<>
void setUniform (const std::string uniform, unsigned int &data)
template<>
void setUniform (const std::string uniform, float &data)
template<>
void setUniform (const std::string uniform, int &data)
template<>
void setUniform (const std::string uniform, unsigned int &data)
template<>
void setUniform (const std::string uniform, float &data)
template<>
void setUniform (const std::string uniform, glm::vec2 &data)
template<>
void setUniform (const std::string uniform, glm::vec3 &data)
template<>
void setUniform (const std::string uniform, glm::vec4 &data)
template<>
void setUniform (const std::string uniform, glm::ivec2 &data)
template<>
void setUniform (const std::string uniform, glm::ivec3 &data)
template<>
void setUniform (const std::string uniform, glm::ivec4 &data)
template<>
void setUniformMatrix (const std::string uniform, bool transpose, glm::mat4 &data)
Private Member Functions
void compileShaderFromSource (const char *source, const std::string &name, GLuint id)
Compiles a shader from source with OpenGL id.
GLint getUniformLocation (const std::string &uniform)
Gets the location of a uniform in a program.
Private Attributes
unsigned int m_numberAttributes = 0
GLuint m_programID
GLuint m_vertexShaderID
GLuint m_fragmentShaderID
Detailed Description
The ShaderProgram is a GLSL program which combines two shaders - the vertex shader and the fragment shader - to allow rendering. Each renderer should have its own program.
Definition at line 14 of file ShaderProgram.hpp.
Constructor & Destructor Documentation
ShaderProgram()
BARE2D::ShaderProgram::ShaderProgram ()
Definition at line 12 of file ShaderProgram.cpp.
References m_fragmentShaderID, m_numberAttributes, m_programID, and m_vertexShaderID.
~ShaderProgram()
BARE2D::ShaderProgram::~ShaderProgram ()
Definition at line 17 of file ShaderProgram.cpp.
Member Function Documentation
compileShaderFromSource()
void BARE2D::ShaderProgram::compileShaderFromSource (const char * source, const std::string & name, GLuint id) private
Compiles a shader from source with OpenGL id.
Parameters
source The source to compile from.
name The name of the shader. This is normally associated with the key in the cache.
id The ID of the shader that has been created with OpenGL calls.
Definition at line 172 of file ShaderProgram.cpp.
References BARE2D::SHADER_COMPILE_FAILURE, and BARE2D::throwFatalError().
Referenced by compileShadersFromSource().
compileShaders()
void BARE2D::ShaderProgram::compileShaders (const char * vertexShaderPath, const char * fragmentShaderPath)
Compiles the shaders. Does not link them.
Parameters
vertexShaderPath The path to the vertex shader
fragmentShaderPath The path to the fragment shader.
Definition at line 21 of file ShaderProgram.cpp.
References compileShadersFromSource(), and BARE2D::IOManager::readFileToBuffer().
Referenced by BARE2D::BasicRenderer::init(), BARE2D::FBORenderer::init(), and BARE2D::ResourceManager::loadShaders().
compileShadersFromSource()
void BARE2D::ShaderProgram::compileShadersFromSource (const char * vertexSource, const char * fragmentSource)
Similar to compileShaders, this just compiles the shaders.
Parameters
vertexSource The source code for the vertex shader
fragmentSource The source code for the fragment shader
Definition at line 33 of file ShaderProgram.cpp.
References compileShaderFromSource(), destroy(), BARE2D::FRAGMENT_SHADER_FAILURE, BARE2D::GLSL_PROGRAM_FAILURE, m_fragmentShaderID, m_programID, m_vertexShaderID, BARE2D::throwFatalError(), and BARE2D::VERTEX_SHADER_FAILURE.
Referenced by compileShaders(), BARE2D::DebugRenderer::init(), and BARE2D::ResourceManager::loadShadersFromSource().
destroy()
void BARE2D::ShaderProgram::destroy ()
Releases all bound objects and deletes any allocated stuff.
Definition at line 161 of file ShaderProgram.cpp.
References m_fragmentShaderID, m_numberAttributes, m_programID, and m_vertexShaderID.
Referenced by compileShadersFromSource(), and BARE2D::Renderer::destroy().
doesUniformExist()
bool BARE2D::ShaderProgram::doesUniformExist (const std::string uniform)
Parameters
uniform The uniform to check for
Returns
True if the uniform is in the compiled shader program, false otherwise.
Definition at line 202 of file ShaderProgram.cpp.
References getUniformLocation().
Referenced by BARE2D::FBORenderer::init().
getUniformLocation()
GLint BARE2D::ShaderProgram::getUniformLocation (const std::string & uniform) private
Gets the location of a uniform in a program.
Parameters
uniform The name of the uniform to find.
Returns
The location of the uniform.
Definition at line 120 of file ShaderProgram.cpp.
References m_programID, BARE2D::throwError(), and BARE2D::UNIFORM_NOT_FOUND.
Referenced by doesUniformExist(), setUniform(), BARE2D::ShaderProgram::setUniform< glm::ivec2 >(), BARE2D::ShaderProgram::setUniform< glm::ivec3 >(), BARE2D::ShaderProgram::setUniform< glm::ivec4 >(), BARE2D::ShaderProgram::setUniform< glm::vec2 >(), BARE2D::ShaderProgram::setUniform< glm::vec3 >(), BARE2D::ShaderProgram::setUniform< glm::vec4 >(), and BARE2D::ShaderProgram::setUniformMatrix< glm::mat4 >().
linkShaders()
void BARE2D::ShaderProgram::linkShaders (std::initializer_list< std::string > attributes)
Links the compiled shaders together to create a coherent shader program.
Parameters
attributes An initializer_list of std::string type of attributes to add to the program. These must link up with the renderer used to draw with this program.
Definition at line 70 of file ShaderProgram.cpp.
References m_fragmentShaderID, m_numberAttributes, m_programID, m_vertexShaderID, BARE2D::SHADER_LINK_FAILURE, and BARE2D::throwFatalError().
Referenced by BARE2D::BasicRenderer::init(), BARE2D::FBORenderer::init(), and BARE2D::DebugRenderer::init().
setUniform() [1/13]
template<> void BARE2D::ShaderProgram::setUniform (const std::string uniform, float & data)
setUniform() [2/13]
template<> void BARE2D::ShaderProgram::setUniform (const std::string uniform, float & data)
Definition at line 234 of file ShaderProgram.cpp.
References getUniformLocation().
setUniform() [3/13]
template<> void BARE2D::ShaderProgram::setUniform (const std::string uniform, glm::ivec2 & data)
Definition at line 279 of file ShaderProgram.cpp.
setUniform() [4/13]
template<> void BARE2D::ShaderProgram::setUniform (const std::string uniform, glm::ivec3 & data)
Definition at line 290 of file ShaderProgram.cpp.
setUniform() [5/13]
template<> void BARE2D::ShaderProgram::setUniform (const std::string uniform, glm::ivec4 & data)
Definition at line 301 of file ShaderProgram.cpp.
setUniform() [6/13]
template<> void BARE2D::ShaderProgram::setUniform (const std::string uniform, glm::vec2 & data)
Definition at line 246 of file ShaderProgram.cpp.
setUniform() [7/13]
template<> void BARE2D::ShaderProgram::setUniform (const std::string uniform, glm::vec3 & data)
Definition at line 257 of file ShaderProgram.cpp.
setUniform() [8/13]
template<> void BARE2D::ShaderProgram::setUniform (const std::string uniform, glm::vec4 & data)
Definition at line 268 of file ShaderProgram.cpp.
setUniform() [9/13]
template<> void BARE2D::ShaderProgram::setUniform (const std::string uniform, int & data)
setUniform() [10/13]
template<> void BARE2D::ShaderProgram::setUniform (const std::string uniform, int & data)
Definition at line 212 of file ShaderProgram.cpp.
References getUniformLocation().
setUniform() [11/13]
template<class T > void BARE2D::ShaderProgram::setUniform (const std::string uniform, T & data)
A generalized wrapper to find and set a uniform for this shader.
Parameters
uniform The name of the uniform in the shader
data The variable to actually set the uniform's value to. This can be a glm::{i,ui,f}vec{1,2,3,4}, an unsigned int, an int, or a float
Definition at line 10 of file ShaderProgram.tcc.
References demangle(), BARE2D::GLSL_PROGRAM_FAILURE, and BARE2D::throwFatalError().
Referenced by BARE2D::FBORenderer::init(), and BARE2D::BasicRenderer::preRender().
setUniform() [12/13]
template<> void BARE2D::ShaderProgram::setUniform (const std::string uniform, unsigned int & data)
setUniform() [13/13]
template<> void BARE2D::ShaderProgram::setUniform (const std::string uniform, unsigned int & data)
Definition at line 223 of file ShaderProgram.cpp.
References getUniformLocation().
setUniformMatrix() [1/2]
template<> void BARE2D::ShaderProgram::setUniformMatrix (const std::string uniform, bool transpose, glm::mat4 & data)
Definition at line 313 of file ShaderProgram.cpp.
setUniformMatrix() [2/2]
template<class T > void BARE2D::ShaderProgram::setUniformMatrix (const std::string uniform, bool transpose, T & data)
Similar to setUniform.
Parameters
uniform The name of the uniform in the shader
transpose Should the matrix be transposed when converted? If false, each matrix is assumed to be supplied in column major order. Else, row major order
data A pointer to the matrix, which is a 1D array of floats, ints, or unsigned ints.
Definition at line 15 of file ShaderProgram.tcc.
References demangle(), BARE2D::GLSL_PROGRAM_FAILURE, and BARE2D::throwFatalError().
Referenced by BARE2D::BasicRenderer::preRender().
unuse()
void BARE2D::ShaderProgram::unuse ()
Deactivates this shader program.
Definition at line 149 of file ShaderProgram.cpp.
References m_numberAttributes.
Referenced by BARE2D::FBORenderer::init(), BARE2D::Renderer::render(), and BARE2D::DebugRenderer::render().
use()
void BARE2D::ShaderProgram::use ()
Activates this shader program for the renderer to use.
Definition at line 136 of file ShaderProgram.cpp.
References m_numberAttributes, and m_programID.
Referenced by BARE2D::FBORenderer::init(), BARE2D::Renderer::render(), and BARE2D::DebugRenderer::render().
Member Data Documentation
m_fragmentShaderID
GLuint BARE2D::ShaderProgram::m_fragmentShaderID private
Definition at line 83 of file ShaderProgram.hpp.
Referenced by compileShadersFromSource(), destroy(), linkShaders(), and ShaderProgram().
m_numberAttributes
unsigned int BARE2D::ShaderProgram::m_numberAttributes = 0 private
Definition at line 79 of file ShaderProgram.hpp.
Referenced by destroy(), linkShaders(), ShaderProgram(), unuse(), and use().
m_programID
GLuint BARE2D::ShaderProgram::m_programID private
Definition at line 81 of file ShaderProgram.hpp.
Referenced by compileShadersFromSource(), destroy(), getUniformLocation(), linkShaders(), ShaderProgram(), and use().
m_vertexShaderID
GLuint BARE2D::ShaderProgram::m_vertexShaderID private
Definition at line 82 of file ShaderProgram.hpp.
Referenced by compileShadersFromSource(), destroy(), linkShaders(), and ShaderProgram().
The documentation for this class was generated from the following files:
Source/ShaderProgram.hpp
Source/ShaderProgram.tcc
Source/ShaderProgram.cpp