BARE2D: BARE2D::Renderer Class Reference
BARE2D::Renderer Class Reference abstract
The renderer class holds some shader program, manages some VBO, some render batch(es), and allows customizable, simple rendering.
#include <Renderer.hpp>
Public Member Functions
Renderer ()
virtual ~Renderer ()
virtual void begin ()
Clears the necessary vectors, etc. to prepare for draw() calls, etc.
virtual void end ()
Creates the renderbatches, does necessary stuff before render() call.
virtual void init ()
Initializes all necessary bits of the renderer.
virtual void initUniforms ()
Initializes all uniforms, such as colour attachments, depth attachments, etc.
virtual void destroy ()
Frees all necessary memory.
virtual void render ()
Actually renders the contents to the screen!
ShaderProgram * getShader ()
Protected Member Functions
virtual void preRender ()
Does stuff inside of the render function, within the shader's use.
virtual void link (std::initializer_list< std::string > attributes)
virtual void createRenderBatches ()=0
Constructs all of the render batches from data given by, say, draw() calls.
Protected Attributes
ShaderProgram m_shader
VAO m_vertexArrayObject
std::vector< RenderBatch > m_batches
Detailed Description
The renderer class holds some shader program, manages some VBO, some render batch(es), and allows customizable, simple rendering.
Definition at line 15 of file Renderer.hpp.
Constructor & Destructor Documentation
Renderer()
BARE2D::Renderer::Renderer ()
Definition at line 7 of file Renderer.cpp.
~Renderer()
BARE2D::Renderer::~Renderer () virtual
Definition at line 10 of file Renderer.cpp.
Member Function Documentation
begin()
void BARE2D::Renderer::begin () virtual
Clears the necessary vectors, etc. to prepare for draw() calls, etc.
Reimplemented in BARE2D::DebugRenderer, and BARE2D::FBORenderer.
Definition at line 13 of file Renderer.cpp.
References m_batches, m_shader, and BARE2D::ShaderProgram::use().
Referenced by BARE2D::DebugRenderer::begin(), and BARE2D::FBORenderer::begin().
createRenderBatches()
virtual void BARE2D::Renderer::createRenderBatches () protected pure virtual
Constructs all of the render batches from data given by, say, draw() calls.
Implemented in BARE2D::BasicRenderer, BARE2D::BumpyRenderer, BARE2D::DebugRenderer, BARE2D::FBORenderer, and BARE2D::TexturelessRenderer.
Referenced by render().
destroy()
void BARE2D::Renderer::destroy () virtual
Frees all necessary memory.
Reimplemented in BARE2D::FBORenderer.
Definition at line 43 of file Renderer.cpp.
References BARE2D::ShaderProgram::destroy(), BARE2D::VAO::destroy(), m_shader, and m_vertexArrayObject.
Referenced by BARE2D::FBORenderer::destroy().
end()
void BARE2D::Renderer::end () virtual
Creates the renderbatches, does necessary stuff before render() call.
Reimplemented in BARE2D::FBORenderer.
Definition at line 20 of file Renderer.cpp.
References m_shader, and BARE2D::ShaderProgram::unuse().
getShader()
ShaderProgram * BARE2D::Renderer::getShader ()
Definition at line 81 of file Renderer.cpp.
References m_shader.
init()
void BARE2D::Renderer::init () virtual
Initializes all necessary bits of the renderer.
Reimplemented in BARE2D::BasicRenderer, BARE2D::DebugRenderer, BARE2D::FBORenderer, and BARE2D::TexturelessRenderer.
Definition at line 25 of file Renderer.cpp.
References BARE2D::VAO::init(), initUniforms(), m_shader, m_vertexArrayObject, BARE2D::ShaderProgram::unuse(), and BARE2D::ShaderProgram::use().
Referenced by BARE2D::BasicRenderer::init(), BARE2D::DebugRenderer::init(), BARE2D::FBORenderer::init(), and BARE2D::TexturelessRenderer::init().
initUniforms()
void BARE2D::Renderer::initUniforms () virtual
Initializes all uniforms, such as colour attachments, depth attachments, etc.
Reimplemented in BARE2D::BumpyRenderer, and BARE2D::FBORenderer.
Definition at line 40 of file Renderer.cpp.
Referenced by init().
link()
void BARE2D::Renderer::link (std::initializer_list< std::string > attributes) protected virtual
Definition at line 85 of file Renderer.cpp.
References BARE2D::ShaderProgram::bindFragOutputLocation(), BARE2D::ShaderProgram::linkShaders(), and m_shader.
Referenced by BARE2D::BasicRenderer::init(), BARE2D::DebugRenderer::init(), BARE2D::FBORenderer::init(), and BARE2D::TexturelessRenderer::init().
preRender()
virtual void BARE2D::Renderer::preRender () inline protected virtual
Does stuff inside of the render function, within the shader's use.
Reimplemented in BARE2D::BasicRenderer, BARE2D::BumpyRenderer, BARE2D::FBORenderer, and BARE2D::TexturelessRenderer.
Definition at line 56 of file Renderer.hpp.
Referenced by render().
render()
void BARE2D::Renderer::render () virtual
Actually renders the contents to the screen!
Reimplemented in BARE2D::BumpyRenderer, BARE2D::DebugRenderer, and BARE2D::FBORenderer.
Definition at line 48 of file Renderer.cpp.
References BARE2D::VAO::bind(), BARE2D::GLContext::bindTexture(), createRenderBatches(), BARE2D::GLContextManager::getContext(), m_batches, m_shader, m_vertexArrayObject, preRender(), BARE2D::GLContext::setActiveTexture(), BARE2D::VAO::unbind(), BARE2D::ShaderProgram::unuse(), and BARE2D::ShaderProgram::use().
Field Documentation
m_batches
std::vector<RenderBatch> BARE2D::Renderer::m_batches protected
Definition at line 67 of file Renderer.hpp.
Referenced by begin(), BARE2D::BasicRenderer::createRenderBatches(), BARE2D::BumpyRenderer::createRenderBatches(), BARE2D::FBORenderer::createRenderBatches(), BARE2D::TexturelessRenderer::createRenderBatches(), render(), BARE2D::BumpyRenderer::render(), and BARE2D::FBORenderer::render().
m_shader
ShaderProgram BARE2D::Renderer::m_shader protected
Definition at line 65 of file Renderer.hpp.
Referenced by begin(), BARE2D::FBORenderer::begin(), destroy(), end(), BARE2D::FBORenderer::end(), getShader(), init(), BARE2D::BasicRenderer::init(), BARE2D::DebugRenderer::init(), BARE2D::FBORenderer::init(), BARE2D::TexturelessRenderer::init(), BARE2D::BumpyRenderer::initUniforms(), BARE2D::FBORenderer::initUniforms(), link(), BARE2D::BasicRenderer::preRender(), BARE2D::BumpyRenderer::preRender(), BARE2D::FBORenderer::preRender(), BARE2D::TexturelessRenderer::preRender(), render(), BARE2D::BumpyRenderer::render(), BARE2D::DebugRenderer::render(), and BARE2D::FBORenderer::render().
m_vertexArrayObject
VAO BARE2D::Renderer::m_vertexArrayObject protected
Definition at line 66 of file Renderer.hpp.
Referenced by BARE2D::BasicRenderer::createRenderBatches(), BARE2D::BumpyRenderer::createRenderBatches(), BARE2D::DebugRenderer::createRenderBatches(), BARE2D::FBORenderer::createRenderBatches(), BARE2D::TexturelessRenderer::createRenderBatches(), destroy(), init(), BARE2D::BasicRenderer::init(), BARE2D::DebugRenderer::init(), BARE2D::FBORenderer::init(), BARE2D::TexturelessRenderer::init(), render(), BARE2D::BumpyRenderer::render(), BARE2D::DebugRenderer::render(), and BARE2D::FBORenderer::render().
The documentation for this class was generated from the following files:
Source/Renderer.hpp
Source/Renderer.cpp